### ISSUE TITLE
Pie chart plot on Jupyter Lab fails to display labels

### ISSUE THREAD

**Issue by chunkylover7** [bqplot/bqplot#1034]
**Describe the bug**
Created a simple pie chart in Jupyter Lab that will not display labels.  Copied a simple pie chart from bqplot's demo Binder page where it displays correctly but again no labels.   While troubleshooting I noticed a few times the labels did show up but were misplaced and mangled together with nonsense numbers where the values were random but the format was 0d:d where d is a 0-9 digit.  I did not get a screen shot and can't get it to reproduce now.  I upgraded bqplot and verified all of the dependencies are met.

I will continue to try to repro the mangled scenario and in the mean time attached are screen shots of the code, data and data type in jupyter as well as version info.  Let me know if there is anything else I can collect.
<img width="809" alt="jupyter code cells" src="https://user-images.githubusercontent.com/10792818/73111046-7710db80-3ece-11ea-874c-09456c631fcf.png">
<img width="583" alt="pie chart - no labels" src="https://user-images.githubusercontent.com/10792818/73111054-7ed08000-3ece-11ea-864b-d13838682125.png">
<img width="438" alt="data and type" src="https://user-images.githubusercontent.com/10792818/73111057-85f78e00-3ece-11ea-9e8e-6578cfc43fcb.png">
<img width="623" alt="misc  dependencies" src="https://user-images.githubusercontent.com/10792818/73111159-ea1a5200-3ece-11ea-863f-b9fa493d81f0.png">
<img width="475" alt="jupyter labextension list" src="https://user-images.githubusercontent.com/10792818/73111163-ed154280-3ece-11ea-9dcc-f1c532803fd1.png">

 
**To Reproduce**

**Expected behavior**
Would expect the labels to print normally and consistently
**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04]
 - Browser [e.g. Firefox, Safari] (if applicable):

**Additional context**

**Comment by martinRenou** [comment]
This should be fixed in recent releases. Please try and update your bqplot version.
