### ISSUE TITLE
Default coloring

### ISSUE THREAD

**Issue by bdch1234** [bqplot/bqplot#1041]
Is there a way to make the default coloring ggplot2-like, i.e. the gray background with white gridlines which are used in the example in the readme.md?

**Comment by martinRenou** [comment]
Sorry for the late answer. You can set the Figure attribute `theme='gg'` in order to get what you want:

![gg](https://user-images.githubusercontent.com/21197331/82416511-70f4cb00-9a7a-11ea-8c62-25037d44b2d3.png)

**Comment by bdch1234** [comment]
Thanks Martin. Is it possible to set themes as default, to avoid having to specify for every figure?

**Comment by martinRenou** [comment]
Apparently yes :)

You can try doing:

```python
from bqplot import Figure
Figure.theme.default_value = 'gg'
```
