### ISSUE TITLE
licensing of notebooks

### ISSUE THREAD

**Issue by jasongrout** [bqplot/bqplot#105]
I think it would be helpful to note the license of the notebooks in the notebooks themselves.

**Comment by dmadeka** [comment]
@jasongrout Do we still want this? I'm doing a major rewrite of the notebooks, and can probably incorporate this. 

If so, do we want the full LICENSE file or just a paragraph?

**Comment by jasongrout** [comment]
I think a line at the bottom would be sufficient. For example, if you wanted to make them CC0 (essentially public domain, which would tell people they should be free to copy the examples, etc.), you can just add the standard one line of boilerplate at the bottom of the example.

**Comment by SylvainCorlay** [comment]
+1 on making the example notebooks CC0.

**Comment by SylvainCorlay** [comment]
Let's close this as we have not used a different license for the notebooks in any widget library.
