### ISSUE TITLE
Removal of convert_to_date breaks example notebook

### ISSUE THREAD

**Issue by jdemeyer** [bqplot/bqplot#1054]
**Describe the bug**
The function `bqplot.traits.convert_to_date` was removed in bqplot-0.12.4. This breaks the example notebook https://github.com/bloomberg/bqplot/blob/master/examples/Advanced%20Plotting/Plotting%20Dates.ipynb

**To Reproduce**
1. Open a new Jupyter notebook and copy/paste the first code block of https://github.com/bloomberg/bqplot/blob/master/examples/Advanced%20Plotting/Plotting%20Dates.ipynb
2. Execute it
3. Observe `ImportError: cannot import name 'convert_to_date' from 'bqplot.traits' (/opt/conda/lib/python3.7/site-packages/bqplot/traits.py)`

**Expected behavior**
Examples should work (and ideally would be tested, for example using nbval)

**Comment by SylvainCorlay** [comment]
Thanks @jdemeyer for the heads up!

**Comment by martinRenou** [comment]
I will revert it
