### ISSUE TITLE
Cannot load bqplot to jupyterlab from dev. js Error: Plugin 'bqplot' failed to activate.

### ISSUE THREAD

**Issue by akmorrow13** [bqplot/bqplot#1057]
Hello,

I tried to clone this repository and install from dev to test in jupyter lab. I get the js console error `Plugin 'bqplot' failed to activate.` 
```
index.js:268 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at JupyterLab.push.2R+v.Application.resolveRequiredService (index.js:182)
```

To install, I ran:

```
cd bqplot
pip install -e .
cd js
jupyter labextension install .
```

Output of  `jupyter labextension list`:
```
JupyterLab v1.2.0
Known labextensions:
   app dir: <path>/miniconda3/envs/JupyterLabv1/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        bdgenomics.mango.pileup v0.0.5  enabled  OK
        bqplot v0.5.5  enabled  OK*

   local extensions:
        bqplot: <path>/bqplot/js
```

How do I properly get the JLab extension running from dev? Thanks in advance.

**Comment by martinRenou** [comment]
I see you cloned `bqplot`. If you are using latest master you should use JupyterLab 2. and the latest version of ipywidgets.

**Comment by akmorrow13** [comment]
Thanks @martinRenou! Where is required version for Jupyter Lab documented? I was unable to find this.

**Comment by acelere** [comment]
@akmorrow13 , have a look at this: [#2798](https://github.com/jupyter-widgets/ipywidgets/issues/2798), it sheds some light. Also, [here](https://github.com/bqplot/bqplot#install-a-previous-bqplot-version) there is a table for front/back-end compatibility.

**Comment by akmorrow13** [comment]
Thanks @martinRenou
