### ISSUE TITLE
Plot becomes unresponsive when given a constant array

### ISSUE THREAD

**Issue by mindv0rtex** [bqplot/bqplot#1071]
**Describe the bug**
Plot becomes unresponsive when given a constant array for `y`.

**To Reproduce**
```
import random

import bqplot.pyplot as plt
import ipywidgets as wg
import numpy as np

y = np.random.randn(100).cumsum()

update_btn = wg.Button(description='Update', button_style='success')

fig1 = plt.figure(animation_duration=750)
line = plt.plot(y)

def on_btn_click(btn):
    val = random.randrange(10)
    if val == 5:
        line.y = np.ones(100) * 0.5
    else:
        line.y = np.random.randn(100).cumsum()

update_btn.on_click(on_btn_click)
wg.VBox([fig1, update_btn])
```
Click the `Update` button a couple of times until the if condition is hit and it will stop responding from then on. It does not display a horizontal line either.

**Expected behavior**
A constant array should be no different from a non-constant one and should not render a plot unresponsive.

**Environment (please complete the following information):**
 - Operating System and Version: OSX Mojave
 - Browser [e.g. Firefox, Safari] (if applicable): Firefox

**Comment by mindv0rtex** [comment]
This is the error I get in the Web Console when the issue occurs:
```
Error setting state: invalid format: .undefinedg
    set_state widget.js:232
    state_change widget.js:213
```

**Comment by mindv0rtex** [comment]
The workaround I was able to find in the meantime is
```
def on_btn_click(btn):
    val = random.randrange(10)
    with line.hold_sync():
        if val == 5:
            line.y = np.ones(100) * 0.5
            line.scales['y'].min = 0
            line.scales['y'].max = 1
        else:
            line.y = np.random.randn(100).cumsum()
            line.scales['y'].min = line.y.min()
            line.scales['y'].max = line.y.max()
```
I found that setting limits to `None` in the `else` clause also triggers the bug, hence the `min()/max()` methods.

**Comment by SylvainCorlay** [comment]
This has been fixed in the latest release! Many thanks for reporting!
