### ISSUE TITLE
0.11.x -> 0.12.x - Difference in date handling

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1073]
We've observed some differences in how dates are displaying in`0.11.x and 0.12.x. For example, with the code below, the tooltip/date axis will display the first date as 2020/30/03 in 0.11.x, and 2020/29/03 in 0.12.x:

```python
import bqplot as bqp
import pandas as pd

x_data = pd.date_range(start='2020-03-30', end='2020-03-31')

scale_y = bqp.LinearScale()
scale_x = bqp.DateScale()

mscat = bqp.Scatter(
    x=x_data,
    y=[1, 2],
    scales={'x': scale_x, 'y': scale_y},
    tooltip=bqp.Tooltip(fields=[ 'y', 'x'],formats=['', '%m/%d/%Y']))

axis_x = bqp.Axis(scale=scale_x)
axis_y = bqp.Axis(scale=scale_y, orientation='vertical')

bqp.Figure(
    marks=[mscat],
    layout={'width':'500px', 'height':'300px'},
    axes=[axis_x, axis_y])
```
0.11.x
![0-11-x](https://user-images.githubusercontent.com/26637211/78691863-fb5be380-78ad-11ea-8844-87d0a0a1dca3.PNG)

0.12.x
![0-12-x](https://user-images.githubusercontent.com/26637211/78691920-06af0f00-78ae-11ea-93de-0b3e5b148d39.PNG)

**Comment by kaiayoung** [comment]
@SylvainCorlay @maartenbreddels for awareness

**Comment by SylvainCorlay** [comment]
So I am not seeing it locally, probably because my time zone is closer to UTC. Looking into it more.

**Comment by SylvainCorlay** [comment]
OK, changing my time zone to PST shows the issue.

**Comment by acelere** [comment]
#967 seems to fix a few issues...perhaps it is worth having a look...

**Comment by SylvainCorlay** [comment]
Yes, thanks @acelere - I was just also playing with `utcFormat`. I think this is the appropriate fix.

**Comment by SylvainCorlay** [comment]
OK, this is fixed in master. Closing.
