### ISSUE TITLE
The bqplot JupyterLab extension should be found by search

### ISSUE THREAD

**Issue by banjaxedben** [bqplot/bqplot#1074]
I use the Extension Manager feature in JupyterLab.
But when I search for "bqplot", it is not listed:
![bqplot_search_result](https://user-images.githubusercontent.com/8545839/79348328-c6decc00-7f2c-11ea-892b-f42676205ba2.png)

I know if I run `jupyter labextension install bqplot` it installs fine.
But it would be nice if the UI option worked too.

**Comment by jasongrout** [comment]
Indeed, it looks like the file https://github.com/bqplot/bqplot/blob/master/js/package.json is missing the `jupyterlab-extension` keyword which is what the extension manager uses to find lab extensions.

**Comment by jasongrout** [comment]
Would you like to make a PR adding that keyword, like in this other extension? https://github.com/jupyter-widgets/ipywidgets/blob/54941b7a4b54036d089652d91b39f937bde6b6cd/packages/jupyterlab-manager/package.json#L9

**Comment by jasongrout** [comment]
We would be changing this file in bqplot: https://github.com/bqplot/bqplot/blob/master/js/package.json

**Comment by SylvainCorlay** [comment]
Thanks! Fixed by @agoose77 in #1082. This will be in the next release.
