### ISSUE TITLE
PanZoom not working with DateScale in 0.12.x

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1078]
It appears that many exceptions on the view side when trying to use the `PanZoom` interaction with a `DateScale` prevent the chart from updating as expected. See the below code:

```python
from bqplot import Lines, LinearScale, DateScale, Axis, Figure
from bqplot.interacts import PanZoom
import numpy as np
import pandas as pd

dates = pd.date_range(end=pd.Timestamp('2020/04/19'), periods=50)

scale_y = LinearScale()
scale_x = DateScale()
line = Lines(x=dates, y=np.random.randn(50), scales={'x': scale_x, 'y': scale_y})

panzoom = PanZoom(scales={'x': [scale_x], 'y': [scale_y]})
Figure(marks=[line],interaction=panzoom)
```

**Comment by kaiayoung** [comment]
@SylvainCorlay @maartenbreddels for awareness

**Comment by SylvainCorlay** [comment]
Fixed in master.

I will be releasing 0.12.8 in the evening including this fix.

Thanks!

**Comment by SylvainCorlay** [comment]
OK, this is not quite correct yet. Looking at it a bit more.
