### ISSUE TITLE
Don't include tests/ package in wheel

### ISSUE THREAD

**Issue by dmcooke** [bqplot/bqplot#1079]
Currently, `pip install bqplot` installs a top-level package 'tests'. This is bad, for what I hope are obvious reasons. The fix is simple: change `find_packages()` call in 'setup.py' to `find_packages(exclude=["tests"])`. (Be sure to nuke the 'build/' directory before rebuilding; otherwise it may still pick up 'tests'.)

**Comment by martinRenou** [comment]
Indeed, I could replicate locally (On a side note: It looks like IPython installs a `tests` module as well, I don't know if this is intentional). I came up with a PR.
