### ISSUE TITLE
GridHeatMap colors don't match axis

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1080]
The colors in the `GridHeatMap` appear to be different than `ColorAxis`. In the code example below, note that the "0" value (bottom left corner) appears to white in the axis, but is different in the heatmap.

```python
from bqplot import *
import pandas as pd
import numpy as np

scale_color = ColorScale(colors=['red', 'white' ,'green'],
                                          max=0.11, mid=0, min=-0.36)
axis_c = ColorAxis(scale=scale_color)
grid_map = GridHeatMap(color=np.array([[-0.13, 0.11],[0,-0.36]]),
                       tooltip=Tooltip(fields=['color']),
                       scales={'color': scale_color})
Figure(marks=[grid_map], axes=[axis_c])
```
<img width="895" alt="Screen Shot 2020-04-20 at 8 25 54 PM" src="https://user-images.githubusercontent.com/26637211/79822745-c5573e80-8346-11ea-9dcb-08546b93bcf3.png">

**Comment by SylvainCorlay** [comment]
cc @rmenegaux :)

**Comment by rmenegaux** [comment]
This problem is not just for the `GridHeatMap` but for all Marks: the `mid` value of the ColorScale domain was incorrectly set.
