### ISSUE TITLE
Bars render incorrectly after new data containing NA's has been assigned. 

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1081]
It appears that the DOM is being manipulated incorrectly if data that contained NA's was previously assigned to the mark. Note the missing bar in the example below:

```python
from bqplot import *
import numpy as np

scale_x = OrdinalScale()
scale_y = LinearScale()
axis_y = Axis(scale=scale_y, orientation='vertical')

data = [[1,2,3],[4,5,7]]

bar = Bars(x=['A', 'B', 'C'],
           y=data,
           scales={'x':scale_x, 'y':scale_y},
           colors=['orange', 'blue'],
           type='stacked')

Figure(marks=[bar], axes=[axis_y])
```
<img width="917" alt="Screen Shot 2020-04-21 at 12 53 03 PM" src="https://user-images.githubusercontent.com/26637211/79908003-5e319c80-83cf-11ea-9462-ce9653469861.png">

```
bar.y = [[1,np.nan,3], [6,3,4]]
```
```
bar.y = data
```

**Comment by kaiayoung** [comment]
@SylvainCorlay @maartenbreddels @ibdafna for awareness

**Comment by SylvainCorlay** [comment]
I think it is a d3.js 5 transition inssue in Bars. We need to check that `exit` is properly called.

**Comment by SylvainCorlay** [comment]
I working on it right now.

**Comment by SylvainCorlay** [comment]
OK, so the issue comes from the fact that NaN were serialized to `null` before the switch to binary serialization, and are now properly serialized as NaNs.

The former was treated as zero, which incidentaly was giving the correct behavior, but now the NaNs propagate.
