### ISSUE TITLE
Selections only working in initially visible tab/accordion containers

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1085]
It appears that selections are only working on `Figure`s in the initially visible tab of ipywidgets containers. In the example below, note that the selection only works on the first tab that is visible. I had thought that this may be related to #1047 , but it seems that some DOM elements for the selector are missing?

```python
from bqplot import *
from ipywidgets import *
from bqplot.interacts import *

scale_x1 = LinearScale()
scale_y1 = LinearScale()
scatter1 = Scatter(x=[1,2,3], y=[3,2,1], scales={'x':scale_x1, 'y':scale_y1})
fig1 = Figure(marks=[scatter1], interaction=BrushSelector(x_scale=scale_x1,
                     y_scale=scale_y1, marks=[scatter1]), background_style={'fill':'#eee'})

scale_x2 = LinearScale()
scale_y2 = LinearScale()
scatter2 = Scatter(x=[1,2,3], y=[3,2,1], scales={'x':scale_x1, 'y':scale_y1})
fig2 = Figure(marks=[scatter2], interaction=BrushSelector(x_scale=scale_x2,
                     y_scale=scale_y2, marks=[scatter2]), background_style={'fill':'#eee'})

tabs = widgets.Tab([fig1,fig2])
tabs.selected_index=0
tabs.set_title(0,'Selector works')
tabs.set_title(1,"Selector doesn't work")

tabs
```

**Comment by maartenbreddels** [comment]
Thanks for the report @kaiayoung. It would be great if you can confirm https://github.com/bqplot/bqplot/pull/1097 fixes it.


> ```python
> scatter2 = Scatter(x=[1,2,3], y=[3,2,1], scales={'x':scale_x1, 'y':scale_y1})
> ```

I guess that should have been `scale_x2` and `scale_y2`?

**Comment by kaiayoung** [comment]
#1097 fixes it!
