### ISSUE TITLE
Lines plot freezes when data is set to all zeroes

### ISSUE THREAD

**Issue by acelere** [bqplot/bqplot#1088]
After creating a Lines plot with random data, changing the y data to all zeroes causes the plot to freeze.
First, create the figure:
```
from bqplot import LinearScale, Lines, Axis, Figure
import numpy as np

x_data = np.arange(0,1000,1)
y_data = np.random.rand(x_data.shape[0])*100
# scales
xs = LinearScale()
ys = LinearScale()

# mark or figure type
line = Lines(x=x_data, y=y_data, scales={'x': xs, 'y': ys})

xax = Axis(scale=xs, label='Sample', grids='on')
yax = Axis(scale=ys, orientation='vertical', grids='on', grid_lines='dashed')

fig = Figure(marks=[line], axes=[xax, yax])
fig
```
Expected behavior: upon changing the data, plot updates:
```
#expected behavior: plot above changes accordingly
y_data = np.random.rand(x_data.shape[0])*100
line.y = y_data
```
Unexpected behavior:  set data to all zeroes, plot freezes:
```
#unexpected behavior: plot freezes
y_data = np.zeros(x_data.shape[0])
line.y = y_data
```
Confirm that plot is frozen:
```
#confirmation that plot is frozen
y_data = np.random.rand(x_data.shape[0])*100
line.y = y_data
```

Attached notebook for convenience.

[bq_lines_issue.zip](https://github.com/bqplot/bqplot/files/4528200/bq_lines_issue.zip)

bqplot version 0.12.6

**Comment by SylvainCorlay** [comment]
Thanks for reporting!

I have found the root cause of the bug and opened a draft PR with a fix.

**Comment by SylvainCorlay** [comment]
Fixed. I am pushing a release of bqplot today which should include that fix!
