### ISSUE TITLE
Dragging incompatible with DateScale 

### ISSUE THREAD

**Issue by joders** [bqplot/bqplot#1108]
When ending a dragging operation the values on an axis of type `DateScale` are corrupted. They change their type from `numpy.datetime64` to `numpy.float64`. In general this happens everytime a message with `"method":"update"` is sent. That also means that if `update_on_move` is set for the mark it happens already immediately after the dragging action is started.

### to reproduce
```
import ipywidgets
import bqplot
import numpy as np
sx = bqplot.DateScale()
sy = bqplot.LinearScale()
ax = bqplot.Axis(scale=sx)
ay = bqplot.Axis(scale=sy, orientation='vertical')
x = np.vectorize(np.datetime64)(["2020-01-01", "2020-01-02", "2020-01-03"])
y = [1., 2., 3.]
mark = bqplot.Scatter(x=x, y=y, scales={'x': sx, 'y': sy})
mark.enable_move = True
#mark.update_on_move = True
fig = bqplot.Figure(marks=[mark], axes=[ax, ay])
ta = ipywidgets.Textarea()
def dr(mark, event):
    ta.value = str(mark.x)
mark.on_drag(dr)
def de(mark, event):
    ta.value = str(mark.x)
mark.on_drag_end(de)
ipywidgets.VBox([fig, ta])
```

### solution
The behavior was investigated already. It was introduced by c62e8a146 where a `slice` operation is supposed to make a copy of an array. In the case of this bug the `slice` should copy a `Float64Array` which has `"type": "date"` attached as attribute. The output of slice does not have the attribute attached. 

The following javascript example demonstrates that `slice` doesn't copy the attributes on an array:

```
a = new Float64Array()
a.myAttribute = "someValue"
b = a.slice()
console.log(a.myAttribute)
console.log(b.myAttribute)    // error: attribute not present
```

There are two options how this can be fixed:

-cleaner fix: not putting foreign attributes on an array. People don't expect attributes to be added to an array and doing so can have unpredictable effects (e.g. if array decides to use such an attribute in the future). So, the type information would have to go somewhere else. It could for instance be part of a class that wraps the array.
-quicker fix: assign and slice: `b = Object.assign(a.slice(), a)` (arrays' attributes stay "polluted")

### recurrences

There are also the following places in the code where attributes would be lost due to the same reasons described above:

```
MarketMap.ts:            const selected = this.model.get("selected").slice();
ScatterBase.ts:            const x = this.model.get('x').slice(); // copy
ScatterBase.ts:            const y = this.model.get('y').slice()
ScatterBase.ts:        let x = this.model.get("x").slice();
ScatterBase.ts:        let y = this.model.get("y").slice();
utils.ts:        return obj.slice()
```

### versions
Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)
bqplot.__version__ == '0.12.9'

**Comment by SylvainCorlay** [comment]
First, many many thanks for investigating this!

I think we should go with the quicker fix (assigning the type following slice operations) because this will be backward compatible in terms of serialization schema.

We could move to a boxed typed at a later stage, for 0.13 for example.

**Comment by joders** [comment]
Thanks for the quick reply.
#1111 fixes all of the occurrences of `slice` where attributes could get lost (see the section 'recurrences' above)
