### ISSUE TITLE
Boxplot not working with arrays of data with different lengths

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1129]
It appears that `BoxPlot()`s can no longer be instantiated with arrays in the `y` trait that have different lengths. See the code below:

```python
from bqplot import *

y_data = [
   [0,1,2,3,4,5,6],
   [0,1,2,3,4,5],
   [0,1,2,3,4,5,6],
]

boxes = Boxplot(x=[1, 2, 3], y=y_data, scales={'x': OrdinalScale(), 'y': LinearScale()})
Figure(marks=[boxes])
```
![err](https://user-images.githubusercontent.com/26637211/81765286-427a5d00-9488-11ea-929b-89220e8fd848.PNG)

**Comment by martinRenou** [comment]
Working on this today.

**Comment by martinRenou** [comment]
It looks like other marks like `Lines` used to support this kind of data as well in `0.11` but gives the same error in `0.12`:

```python
from bqplot import *

x_sc = LinearScale()
y_sc = LinearScale()

y_data = [
   [0,1.5,2,3,4,5,6],
   [0,1,2,2,3],
   [0,2,6,10,4,5,6],
]

line = Lines(x=[1, 2, 3,4,5,6,7], y=y_data, scales={'x': x_sc, 'y': y_sc})

ax_x = Axis(scale=x_sc, label='x')
ax_y = Axis(scale=y_sc, orientation='vertical', label='y')

Figure(marks=[line], axes=[ax_x, ax_y])
```

It has to do with the binary serialization which does not support data that is not representable as a NumPy array. We need to fix the array serialization logic.
