### ISSUE TITLE
Lines not drawing correctly with multidimensional data

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1131]
HI team, it appears that lines are not being drawn correctly when a `Lines()` widget is instantiated with multidimensional data, and then later 1D data is assigned. For example:

```python
from bqplot import *
line = Lines(x=[1,2,3],
             y=[[1,2,3],[2,3,4]],
             scales={'x':LinearScale(), 'y':LinearScale()})
Figure(marks=[line])
```

```python
line.y = [3,4,5]
```

<img width="1019" alt="Screen Shot 2020-05-14 at 5 09 11 PM" src="https://user-images.githubusercontent.com/26637211/81998028-4f24bf80-9606-11ea-8309-bcf89aac5832.png">

**Comment by SylvainCorlay** [comment]
This has been fixed in master!

**Comment by martinRenou** [comment]
Yes this one should have been fixed by https://github.com/bqplot/bqplot/pull/1126
