### ISSUE TITLE
Pan moving patch diagonally instead of with the image viewer

### ISSUE THREAD

**Issue by javerbukh** [bqplot/bqplot#1157]
![Jun-09-2020 11-19-45](https://user-images.githubusercontent.com/7179333/84166664-3069eb00-aa43-11ea-9ec3-c1b2b60b4d1f.gif)

I created a thin rectangle over a `bqplot image viewer` using the following code:
```
ls = LinearScale()
scales={'x': ls, 'y': ls}

patch = bqplot.Lines(x=x, y=y, scales=scales, fill='none', colors = ["red"], stroke_width=2, close_path=True)

fig.marks = fig.marks + [patch]
```

When I pan up and down, the rectangle moves diagonally left-down and diagonally right-up, respectively. However, when I pan left to right, the rectangle does not move at all. Is this a problem with the scales I am using?

**Comment by maartenbreddels** [comment]
> ls = LinearScale()
> scales={'x': ls, 'y': ls}

You have the x and y scale the same object. By panning, the scale's min and max are adjusted, and they point to the same widget/object. You probably want to have two scales. I have to say I don't fully understand why nothing happens when you move left/right. Also, if you explicitly create a PanZoom object, you give a dict of lists, e.g. :
```
fig.interaction = PanZoom(scales={'x': [scale_x1, scale_x2], 'y': [scale_y]})
```
Which says which scales the PanZoom interact affects. In this case, you probably want the y scale of the Lines object/widget not to be effected.

does that make sense?

**Comment by javerbukh** [comment]
So I made both the x and y scales `LinearScale()` and got the following:
<img width="448" alt="Screen Shot 2020-06-10 at 7 09 04 AM" src="https://user-images.githubusercontent.com/7179333/84261413-b9d3f880-aae9-11ea-9359-d8e5881f0dd2.png">

Then I made x `OrdinalScale()` like it was before and got the following (also, left-right pan still does not work here):
<img width="473" alt="Screen Shot 2020-06-10 at 7 13 11 AM" src="https://user-images.githubusercontent.com/7179333/84261546-f0aa0e80-aae9-11ea-8868-f81639cacc00.png">

Neither of which looks like the first graphic in this ticket. I do not understand why this is happening but it's probably because I am inexperienced with working with different types of `Scales` in bqplot. I will try to create a PanZoom object and see if that changes the left-right pan interaction.

Just for more clarity, here is the code that creates the points on the plot where the Line will go:
```
def region_to_vertices(region):
    p = region.to_polygon()
    return p.vertices.x, p.vertices.y

# Make an example region
region = RectanglePixelRegion(center=PixCoord(0,0), 
                              width=.1, 
                              height=2)
# Get corners
x, y = region_to_vertices(region)

**Comment by javerbukh** [comment]
Same solution as #1161, closing this ticket.
