### ISSUE TITLE
Text location

### ISSUE THREAD

**Issue by npschafer** [bqplot/bqplot#1162]
https://github.com/bqplot/bqplot/blob/ac85a703f404be4e5209787ca576fefd76da25c4/js/src/Scatter.ts#L192

Thanks for taking the time to make such an awesome package and for releasing it for free and as open source.

I would rather not have my point labels ('names') offset by (text_loc, -text_loc) (see the above line reference). Is there any way to accomplish this without directly editing the Scatter.ts file?

Cheers

**Comment by ibdafna** [comment]
I'll take a look to see if we can add something on the python side to control this behaviour.

**Comment by ibdafna** [comment]
Implemented in #1168
