### ISSUE TITLE
BQPlot 0.12.12 Stacked bar opacities set on a group level and not individual bars

### ISSUE THREAD

**Issue by ibdafna** [bqplot/bqplot#1163]
Hi team,

There's a change in behaviour between bqplot 0.11.6 and 0.12.12 where setting opacities for a stacked bar plot applies the opacities on the entire bar group (all layers) in version 0.12.12, as opposed to each individual bar layer in 0.11.6. The expected behaviour is that of 0.11.6. See the code below to reproduce:

```python
from bqplot import OrdinalScale, LinearScale, Bars, Axis, Figure

x_ord = OrdinalScale()
y_sc = LinearScale()

bar = Bars(x=[0, 1], y=[[1.5, 1.5], [2.5, 2.5], [3.5, 3.5]], 
           scales={'x': x_ord, 'y': y_sc}, 
           labels=['Dim 1', 'Dim 2', 'Dim 3'], display_legend=True, opacities=[1, 0.7, 0.1, 0.1, 0.7, 1])
ax_x = Axis(scale=x_ord)
ax_y = Axis(scale=y_sc, orientation='vertical')

Figure(marks=[bar], axes=[ax_x, ax_y])
```
This is a screenshot from version 0.11.6, with the expected behaviour:
![image](https://user-images.githubusercontent.com/24281433/84719182-83560d80-af2f-11ea-8c8b-8a0ffb956330.png)

That is a screenshot from 0.12.12, where opacities are applied group-wise:
![image](https://user-images.githubusercontent.com/24281433/84719125-5b66aa00-af2f-11ea-9a43-defd37b3e790.png)

Many thanks

**Comment by ibdafna** [comment]
@SylvainCorlay for awareness

**Comment by martinRenou** [comment]
Assigning myself. I'll have a look.

**Comment by martinRenou** [comment]
What should be the behavior actually? I assumed the behavior should be the same with colors, so I tried the following:

```python
from bqplot import OrdinalScale, LinearScale, Bars, Axis, Figure

x_ord = OrdinalScale()
y_sc = LinearScale()

bar = Bars(x=[0, 1], y=[[1.5, 1.5], [2.5, 2.5], [3.5, 3.5]], 
           scales={'x': x_ord, 'y': y_sc}, 
           labels=['Dim 1', 'Dim 2', 'Dim 3'], display_legend=True, opacities=[1, 0.7, 0.1, 0.1, 0.7, 1], 
           colors=['red', 'orange', 'yellow', 'yellow', 'orange', 'green'])
ax_x = Axis(scale=x_ord)
ax_y = Axis(scale=y_sc, orientation='vertical')

Figure(marks=[bar], axes=[ax_x, ax_y])
```
And this is what I get with bqplot 0.11.6:

![bqplot_0 11 6](https://user-images.githubusercontent.com/21197331/84996152-2f287480-b14d-11ea-8f50-4b11b0409868.png)

And with master:

![bqplot_0 12](https://user-images.githubusercontent.com/21197331/84996234-48312580-b14d-11ea-9cc6-536b5cba2e66.png)


So it looks like with 0.11:
- We cycle through opacities for all the layers
- We cycle through colors stack-wise

And with 0.12:
- We cycle through opacities stack-wise
- We cycle through colors stack-wise

0.12 is more homogeneous, but I am wondering what should be the actual behavior? The approach you were expecting gives more freedom, but I also feel like it's less natural.

**Comment by ibdafna** [comment]
Hey, thanks for taking a look!

I guess one way to answer that question is how would these be coloured if they were grouped rather than stacked? I would expect them to still have varying opacities rather than have a single opacity group-wise. What do you think?

**Comment by martinRenou** [comment]
Actually I just found there is a `color_mode` attribute, that allow you to colorize the bars per-group, or per-element.

### Grouped + color_mode group
![color_mode](https://user-images.githubusercontent.com/21197331/85105215-601aaf00-b20a-11ea-96c2-266fba930869.png)

### Grouped + color_mode element
![group_element](https://user-images.githubusercontent.com/21197331/85105295-893b3f80-b20a-11ea-9180-705595729795.png)

### Stacked + color_mode group
![stacked_group](https://user-images.githubusercontent.com/21197331/85105372-b4be2a00-b20a-11ea-8a0a-8a3e638398ac.png)

### Stacked + color_mode element
![stacked_element](https://user-images.githubusercontent.com/21197331/85105374-b7208400-b20a-11ea-817c-bb2e57f1c822.png)


So what about introducing a new `opacity_mode` attribute?

**Comment by martinRenou** [comment]
Even better, we could revert to the `0.11.x` behavior now, and later on introduce an `opacity_mode` attribute. What do you think?

**Comment by ibdafna** [comment]
Awesome, yeah, I agree it would make sense to align the behavior of the color and opacity traits. I also tested the color mode before, and what I observed, which is consistent with your observation, is that one color is used per bar - the opacities will vary, but for the same color. 

So in the example above, we have the "red" and "orange" colors applied. Their application depends on whether color_mode is set to "group" or "element", but effectively we have two colors for two bar groups. That's probably also something to consider if we want to align the behavior of the two :)

Your assessment of how to handle this makes sense, I think! "group" should apply colors/opacities on a group basis. So we have have a particular bar group with **n** bars, one color will be applied to all **n** bars in that group. The opacities could then be also applied on a group basis, so the same opacity for all bars or, if on an element basis, different opacity for each bar in that group. The same logic would apply to "element" option with colors, we should be able to apply a different color so each bar when setting the color_mode to "element". Here is a more concrete example: 

If we have 3 bar groups, with 2 bars on each group, setting "color_mode:element" and passing a list of 6 unique colors should result in all bars having unique colors. With "color_mode:group", only the first 2 colors from the color list will be used - 1 per group, and all bars in that group will have the same color. The exact same logic could then apply to the opacities. 

Is this what you had in mind, or would consider? And many thanks for the work you already put in to this with the PR!

**Comment by martinRenou** [comment]
> I think my description of "element" is your proposal with "real_element" above. I think having all three options does make sense!

Cool! I don't like the "real_element" name though. And we might want to keep the "element" name as it currently behaves for the color_mode for backwards compatibility, what do you think?

**Comment by ibdafna** [comment]
Yeah, agreed on keeping the "element" name. As for a name for the new mode, maybe "cycle" or something like it? Trying to avoid using the "element" keyword here, although "cycle_elements" could also work. I'm not strongly opinionated on the naming, anything that you think makes sense!

**Comment by martinRenou** [comment]
I don't really like "cycle", as other modes are also cycling, but not on the same entities. What do you think about "mark"? My idea is that "group" refers to a group of element, "element" refers to group elements, and "mark" would refer to all the marks?

**Comment by ibdafna** [comment]
I think that makes sense. We can also use "no_group" to say we're not applying any sort of grouping logic. I'm okay with either! Feel free to make the call :)

**Comment by martinRenou** [comment]
Good idea, I prefer "no_group" :) I'll update my PR then.

**Comment by martinRenou** [comment]
I updated my PR. Please tell me what you think :)
