### ISSUE TITLE
Saving figure png doesn't include image mark

### ISSUE THREAD

**Issue by cmegan** [bqplot/bqplot#1174]
I created a figure that has an Image mark as the background of a scatter plot where I can move the points around. When I display the figure in Jupyter, everything looks as I expect, but when I click the save button on the toolbar, the saved png only displays the scatter plot points (the image mark doesn't appear in the png). Is there a way to get the image mark to appear in the saved png? (The zoom and reset buttons of the toolbar work perfectly, the save is the only thing not working).

imx = bq.LinearScale()
imy = bq.LinearScale()
im = bq.Image(image=im, scales={'x': imx, 'y': imy}
s = bq.Scatter(x=x_data, y=y_data, scales={'x': imx, 'y': imy}, enable_move=True, colors=['red'])
fig = bq.Figure(marks=[im, s], animation_duration=200, padding_x=0, padding_y = 0)
t = bq.toolbar.Toolbar(figure=fig)
display(fig, t)

**Comment by rosteen** [comment]
+1, I also just hit this bug trying to implement figure saving in [jdaviz](https://github.com/spacetelescope/jdaviz), where we're using bqplot for all our plotting. Line charts save out fine, but both `Figure.save_svg` and `Figure.save_png` result in images with only the axes shown. 

Image viewer screenshot:
<img width="323" alt="image_expected" src="https://user-images.githubusercontent.com/39831871/88839378-f8606800-d1a8-11ea-8819-ac67e9389e09.png">

Resulting saved image:
![image_test](https://user-images.githubusercontent.com/39831871/88839410-044c2a00-d1a9-11ea-97e8-6305079e132c.png)
