### ISSUE TITLE
How to align x ticks under the x axis?

### ISSUE THREAD

**Issue by NorbertH14** [bqplot/bqplot#1197]
Hi there,

I have some problems in formatting my barplot and I need help. My bqplot version is 0.12.16 
My example code looks like this:

```
actual_data = [20,4,6,4,30]
actual_labels = ['AAAAAAAAAAAAAAAAAAAAAAA', "BBBBBBB BBBBBBBBBBB", "CCCC CCCC CCCCCC", "DDDDDDDDDDDDDDDDD DDDDDDDD", "EEEEEEEEEE"]

x_sc = OrdinalScale()
y_sc = LinearScale()

ax_x = Axis(label='x axis', scale=x_sc, grid_lines='solid', tick_rotate=45, label_offset='30')
ax_y = Axis(label='y axis', scale=y_sc, orientation='vertical',tick_format='0.2f', label_offset='-44')

bar = Bars(x=actual_labels, y=actual_data, scales={'x': x_sc, 'y': y_sc}, padding=0.8)

fig_bars = Figure(marks=[bar], axes=[ax_x, ax_y], title='Test')
fig_bars

```
![image](https://user-images.githubusercontent.com/36290014/91630818-0803e400-e9d5-11ea-863f-b9aefc8a04be.png)

Is it possible to align the x ticks to the left, rotated 90 or 45 deg (already done) and under the x axis?
This solution from stackoverflow didn't work 
[bqplot - Tick placement outside of plot](https://stackoverflow.com/questions/59988632/bqplot-tick-placement-outside-of-plot)

Thanks a lot

Norbert

**Comment by maread99** [comment]
`fig_bars.axes[0].tick_style = {'text-anchor': 'start'}`

![image](https://user-images.githubusercontent.com/56914820/93574358-3b141480-f990-11ea-8299-68ef4ada6223.png)

Various style attributes in bq can take a dictionary of CSS properties. The following options work for some objects (trial and error):
'fill': 'blue'
'font-size': '16px'
'font-family': 'Verdana'
'stroke': 'yellow'
'stroke-width': '5'
'opacity': 0.5
'background-color': 'white'
'border-color': 'yellow'
'border-width': '5px'  # can be defined as px, pt, cm, em, Literal['thin', 'medium', 'thick']
'color': 'red'  # sometimes covers text color
'line-height': 0.5  # height between lines of text
'text-anchor' : 'end'  # Literal['end', 'start', 'middle']
'font-weight': 'bold'
'font-style': 'italic'

**Comment by ChakriCherukuri** [comment]
@NorbertH14 sorry for the delay. 
IMHO using horizontal bar charts is better when labels are large. You can do it using `pyplot` like so:

```python
fig = plt.figure(title='Test',  fig_margin=dict(top=60, bottom=20, left=250, right=20))
x = ['AAAAAAAAAAAAAAAAAAAAAAA', "BBBBBBB BBBBBBBBBBB", "CCCC CCCC CCCCCC", "DDDDDDDDDDDDDDDDD DDDDDDDD", "EEEEEEEEEE"]
y = [20, 4, 6, 4, 30]
bars = plt.bar(x, y, orientation='horizontal', padding=.6, axes_options={'x': {'grid_lines': 'none'}})
fig
```
<img width="997" alt="Screen Shot 2020-09-21 at 9 59 58 PM" src="https://user-images.githubusercontent.com/5638994/93837886-cf62cd80-fc55-11ea-856a-56028a9e2ef0.png">

Note the use of `fig_margin` with a large value of `left` attribute to accommodate the labels.
Please let me know if this solutions works for you.

**Comment by NorbertH14** [comment]
@maread99 @ChakriCherukuri 
First of all, thanks for your answer. 
I think that both solutions will work for me and will give me some options.
