### ISSUE TITLE
bqplot 0.12.17 Error displaying widget: model not found

### ISSUE THREAD

**Issue by john518** [bqplot/bqplot#1210]
I just installed jupyter lab 2.2.8 and bqplot 0.12.17 on a windows 10 machine (Python 3.8.3 in venv). The bqplot example line chart displays OK in Jupyter notebook but fails in Jupyter Lab with the message "model not found".

* In the js console are numerous error messages of the form `widget model not found`, `Could not instantiate widget`, and `Could not create a model`.
* Further down are some more interesting error messages of the form `Error: Module bqplot, semver range ^0.5.17 is not registered as a widget module`
* I tried `jupyter lab clean` and `jupyter lab build` but no change.

Any idea what's going wrong? Feels like my js code is out of sync with the python code, but I don't know how to debug or fix.

**Comment by ibdafna** [comment]
Did you run the following commands after installing bqplot?
````bash
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager # install the Jupyter widgets extension
$ jupyter labextension install bqplot
````

**Comment by john518** [comment]
Oh, thanks. I didn't see that in the docs - did I miss something? Regardless, all good now.
