### ISSUE TITLE
Source distribution is broken.

### ISSUE THREAD

**Issue by maartenbreddels** [bqplot/bqplot#1234]
To reproduce:
```
$ python setup.py -v sdist  
$ pip install -v  dist/bqplot-0.12.18.tar.gz
....
running bdist_wheel
  running jsdeps
  Installing build dependencies with npm.  This may take a while...
  > npm install
  error: [Errno 2] No such file or directory: '/private/var/folders/4h/rklzvjwj08170p1nlsntfdkw0000gn/T/pip-req-build-8ge5c6k1/js': '/private/var/folders/4h/rklzvjwj08170p1nlsntfdkw0000gn/T/pip-req-build-8ge5c6k1/js'
  Building wheel for bqplot (PEP 517) ... error
  ERROR: Failed building wheel for bqplot
....
```

This seems to be caused by 0467ef1e901b5d50bfb850639bcde06172e634fe where we now rely on jupyter_packaging. However, we first checked if all our targets already existed, and this feature does not seem to be present in jupyter_packing.

Solution:
I propose we revert 0467ef1e901b5d50bfb850639bcde06172e634fe so we can continue doing releases, and see how we can push this in jupyter_packaging.

**Comment by martinRenou** [comment]
> and see how we can push this in jupyter_packaging

What do you want to push in jupyter-packaging?

**Comment by maartenbreddels** [comment]
The feature that is now missing from setup.py, e.g. skip_if_exists in #1235
