### ISSUE TITLE
d3-selection-multi does not work in federated bundle when ipyvolume is installed

### ISSUE THREAD

**Issue by maartenbreddels** [bqplot/bqplot#1245]
Installing #1222 and https://github.com/maartenbreddels/ipyvolume/pull/355
we get: 
this.fig_background.append(...).attr(...).attr(...).attr(...).attr(...).attr(...).styles is not a function
Which should be provided by https://github.com/d3/d3-selection-multi/blob/master/index.js

For some reason the d3 instance is shared between ipyvolume and bqplot, and bqplot gets the wrong one?

Note that this issue shows up even when not using ipyvolume at all.

**Comment by maartenbreddels** [comment]
@jasongrout i thought bqplot and ipyvolume cannot affect each other with the federated bundles. It it possible that bqplot gets ipyvolume's d3 version, which is not money patched by 'd3-selection-multi' ? I thought by default packages are not shared.

**Comment by maartenbreddels** [comment]
By default bundled is true, maybe false will work (source https://github.com/jupyterlab/jupyterlab/issues/9496#issuecomment-749381599 )

**Comment by maartenbreddels** [comment]
Fixed by https://github.com/bqplot/bqplot/pull/1222/commits/3181faf0470e621c977822d257d32f05d6ca01e8

**Comment by jasongrout** [comment]
> I thought by default packages are not shared.

By default, all direct dependencies are shared. See https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#deduplication-of-dependencies

**Comment by agoose77** [comment]
This can be closed?

**Comment by maartenbreddels** [comment]
Yes, the magic line was https://github.com/bqplot/bqplot/pull/1222/files#diff-e51a40ac250c9696142466f114f754161e7e5102c0cdb5354548b757deb272f6R89
