### ISSUE TITLE
bqplot on python 3.9 in conda-forge?

### ISSUE THREAD

**Issue by JuanCab** [bqplot/bqplot#1246]
I normally install packages from conda-forge... noticed bqplot was not available under python 3.9 yet. Is this an issue with the condo-forge feedstock of bqplot or is there a problem with bqplot under python 3.9?

**Comment by ibdafna** [comment]
Duplicate of https://github.com/conda-forge/bqplot-feedstock/issues/69.

Closing

**Comment by JuanCab** [comment]
I apologize for the duplicate, but both reports should not be closed!

**Comment by JuanCab** [comment]
Sorry for the duplicate.
