### ISSUE TITLE
Jupyter lab widget not working with 0.12.18

### ISSUE THREAD

**Issue by tiagopereira** [bqplot/bqplot#1253]
**Describe the bug**
This is the same error as in https://github.com/bqplot/bqplot/issues/884. When loading a bqplot widget in jupyter lab, I get

```
Error displaying widget: model not found
```

This used to work before, but now with a clean install, I can't get it to work again.

**To Reproduce**
Installed jupyterlab, bqplot, and nodejs from conda:

```
# Name                    Version                   Build  Channel
bqplot                    0.12.18            pyh9f0ad1d_0    conda-forge
nodejs                    15.3.0               heaeed3d_0    conda-forge
jupyterlab                3.0.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.0.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
```

Then installed the lab extension (bqplot v0.5.19) with:

```
$ jupyter lab extension install bqplot
```

Also tried installing `@jupyter-widgets/jupyterlab-manager` beforehand, but get the same result. Tried forcing `bqplot@0.4.6` (suggested in #884), still same problem.

**Expected behavior**
Expected the bqplot widget to show on jupyter lab.

**Additional context**
It would be nice to know a combination of versions that works. This was a clean install, and the extensions I have are:

```
$ jupyter labextension list
JupyterLab v3.0.1
/Users/user/miniconda/envs/solarnet/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /Users/user/miniconda/envs/solarnet/share/jupyter/lab
        bqplot v0.5.19 enabled OK
```

**Comment by martinRenou** [comment]
Thanks for reporting, bqplot does not work yet with JupyterLab 3 see https://github.com/bqplot/bqplot/pull/1222

**Comment by martinRenou** [comment]
The latest release of bqplot now works with JupyterLab 3, we can close this issue
