### ISSUE TITLE
Bar labels not displayed

### ISSUE THREAD

**Issue by chuckmandu** [bqplot/bqplot#1275]
**Describe the bug**
[This PR (#974, merged 10/12/2019)](https://github.com/bqplot/bqplot/pull/974), was intended to allow bars in the Bars mark to have value labels displayed for each bar, as shown:
![image](https://user-images.githubusercontent.com/78721320/107676988-9a7c0500-6c4e-11eb-876e-6611a5e8143f.png)

The examples accompanying it illustrate this successfully for both stacked/grouped and ungrouped bar charts.

However, Bar labels are **not displayed** for Bars when running bqplot version 0.12.21, as shown with the following example:

**To Reproduce**
```
import bqplot as bqp
import numpy as np`

x_ord = bqp.OrdinalScale()
y_sc = bqp.LinearScale()

bar = bqp.Bars(x=np.arange(10), y=np.arange(-5, 5), scales={'x': x_ord, 'y': y_sc},
               label_display=True,
               label_display_vertical_offset=-13,
               label_font_style={"fill": "black",
                                 "font-size": "12px"})

ax_x = bqp.Axis(scale=x_ord, orientation='vertical')
ax_y = bqp.Axis(scale=y_sc, tick_format='0.2f')

bqp.Figure(marks=[bar], axes=[ax_x, ax_y], padding_x=0.025, padding_y=0.05)
```

![image](https://user-images.githubusercontent.com/78721320/107677257-eb8bf900-6c4e-11eb-8062-77f850e332ea.png)

**Comment by martinRenou** [comment]
I cannot reproduce the issue you are reporting with master nor with 0.12.21. Could you give us more information about your installation showing the output of the following commands?Is it 
```
jupyter nbextension list

# or if you use JupyterLab:

jupyter labextension list

# and 

pip list | grep bqplot

# or 

conda list | grep bqplot
```

**Comment by chuckmandu** [comment]
Here you go:

Known nbextensions:
  config dir: /home/dschofield/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK

pip list| grep bqplot
bqplot                        0.12.1

**Comment by chuckmandu** [comment]
Interesting discovery:
When I execute the code sample (above) using Voila, it works as expected, with bar labels displayed:
![image](https://user-images.githubusercontent.com/78721320/110062450-1e8d4e00-7d1e-11eb-969e-5fb9fa444912.png)

**Comment by martinRenou** [comment]
If you still cannot make it work, I'd suggest trying again from a clean environment. I suppose you don't have an up-to-date front-end extension.
