### ISSUE TITLE
Zoom is not working anymore 

### ISSUE THREAD

**Issue by maartenbreddels** [bqplot/bqplot#1304]
Example code
```
import numpy as np
from bqplot import pyplot as plt

plt.figure(1, title='Line Chart')
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x, y)
plt.show()
```

Now clicking the panzoom button, we don't have a working zoom anymore.

This was originally reported downstream at https://github.com/spacetelescope/jdaviz/issues/486 and the upstream issue 
at https://github.com/d3/d3-zoom/issues/231

This affects Chrome 89.0.4389.90 (OSX), and is demonstrated by zoom not working at: https://observablehq.com/@philjones/zoom-svg-chrome-89-0-4389-90-bug

**Comment by maartenbreddels** [comment]
Weirdly, after upgrading Chrome (still reporting the same version!) https://observablehq.com/@philjones/zoom-svg-chrome-89-0-4389-90-bug works 🤷

**Comment by maartenbreddels** [comment]
@sntgluca does https://observablehq.com/@philjones/zoom-svg-chrome-89-0-4389-90-bug work for you?

**Comment by sntgluca** [comment]
@maartenbreddels ,

interesting.

With the link above I can _zoom correctly_ with
* **Chrome** Version 90.0.4430.93 (Official Build) (x86_64)
* **Edge** Version 90.0.818.42 (Official build) (64-bit)
while it _doesn't work_ with **Safari** Version 14.1 (15611.1.21.161.5, 15611)

With a Jupyter notebook I can zoom correctly with **Edge** and it _doesn't work_ with either **Chrome** or **Safari**.

**Comment by acelere** [comment]
The link works for me on Firefox 88 (64 bit)

**Comment by pllim** [comment]
Hmm. Maybe this is also why I cannot zoom over at spacetelescope/jdaviz#564 ?

**Comment by maartenbreddels** [comment]
@pllim yes, I linked to https://github.com/spacetelescope/jdaviz/issues/486 so i guess those are duplicates.

**Comment by giswqs** [comment]
I have the same issue with bqplot v0.12.26. Zooming is no longer working.
