### ISSUE TITLE
are bqplot and VSCode-Python compatible, under Jupyterlab-3-only new world ?

### ISSUE THREAD

**Issue by stonebig** [bqplot/bqplot#1310]
hi,

Trying to use now Bqplot as a pure "jupyterlab-3" plugin",  I have issues when trying to use it in VSCode-Python.
Does anyone knows if it is suppose to work well ? (I only do `pip install bqplot` now)

![image](https://user-images.githubusercontent.com/4312421/112720654-f39eb000-8eff-11eb-8ce2-df29b78f81ff.png)

**Comment by martinRenou** [comment]
Hello.

The example in your screenshot is not using bqplot. Could it be the wrong screenshot?

**Comment by stonebig** [comment]
Oups! Will recheck this week-end

**Comment by martinRenou** [comment]
Actually, they do support custom widgets, but you need to install the Jupyter plugin to have it working. See this issue for bqplot screenshots in vscode: https://github.com/microsoft/vscode-jupyter/issues/995

**Comment by stonebig** [comment]
ok, retesting:
- the above problem is  something related to another library,
- the problem with bqplot, is now that I'm 100% jupyterlab, it seems VSCode wants to download something from internet
![image](https://user-images.githubusercontent.com/4312421/113483292-f28ef500-94a2-11eb-8e9f-70dbfc967836.png)

I don't know how to pre-load that, how it wsa not a problem with legacy Jupyter notebook

**Comment by stonebig** [comment]
hum, If I launch it slowly in VSCode, it seems I don't have the issue anymore
