### ISSUE TITLE
Jupyter Lab build fails with 0.5.25

### ISSUE THREAD

**Issue by athornton** [bqplot/bqplot#1319]
**Describe the bug**
New version 0.5.25 fails with JupyterLab 2.3.1

**To Reproduce**
jupyter lab build --dev-build=False --minimize=False, with the following modules enabled (I'm sure there's a more concise way to get here, probably just with bqplot, but I haven't done that, because 0.5.23 still works and I need to get my build moving again before tonight):

"@jupyterlab/toc \
          bqplot \
          ipyevents \
          ipyvolume \
          jupyter-threejs \
          nbdime-jupyterlab \
          dask-labextension \
          @jupyter-widgets/jupyterlab-manager \
          jupyter-matplotlib@^0.9.0 \
          @pyviz/jupyterlab_pyviz \
          jupyterlab_iframe \
          @jupyter-widgets/jupyterlab-sidecar \
          @bokeh/jupyter_bokeh \
          pywwt \
          jupyter_firefly_extensions \
          @jupyterlab/hdf5 \
          @lsst-sqre/rubin-labextension-query \
          @lsst-sqre/rubin-labextension-savequit \
          @lsst-sqre/rubin-labextension-displayversion"

The debug error log says:

```
    ERROR in ./node_modules/bqplot/shaders/scatter-vertex.glsl 1:0
    Module parse failed: Unexpected character '#' (1:0)
```

So I'm guessing that something's trying to parse that #include statement and failing?

**Expected behavior**

Jupyterlab build to work.

**Screenshots**

**Additional context**

0.5.23 works fine.

**Comment by athornton** [comment]
Maybe some new test is trying to parse the shader files as JSON and doesn't know to exclude them?

**Comment by martinRenou** [comment]
Thanks for reporting. Yes there are been some recent changes on the way we load those shaders. I am surprised it doesn't work though.

Note that if you are using JupyterLab v3, you don't need to build JupyterLab with the extension included in it. So no need to run `jupyter labextension install bqplot`. This might be a way for you to workaround this issue for now.

**Comment by athornton** [comment]
I am greatly looking forward to moving to JL3 (and packaging the Rubin Observatory extensions as prebuilt).  It's on our roadmap but hasn't been scheduled yet.  That won't be a near-term workaround, but our long-term intended direction.

For the moment I can get by fine with bqplot 5.0.23, and I expect that would serve until we can move into a JL3 world.

I have no evidence to support this, but I kind of suspect `yarn prettier` to be the culprit.  Hating a hash character _smells_ like something expecting JSON.

**Comment by martinRenou** [comment]
I will debug this today. It seems unlikely to me that `yarn prettier` is the culprit, it should not be run when building lab, but I might be wrong.

**Comment by martinRenou** [comment]
Opening a PR to expose the issue: https://github.com/bqplot/bqplot/pull/1320

We should maybe revert [this PR](https://github.com/bqplot/bqplot/pull/1291) for now as I think is the culprit.

**Comment by martinRenou** [comment]
This should work with the latest release now :) Thanks for reporting
