### ISSUE TITLE
Background Question - Not an Issue

### ISSUE THREAD

**Issue by russ-mcbride** [bqplot/bqplot#1327]
I'm hoping a little more background can be provided in the README. Ultimately, I'm trying to understand appropriate use cases that might help me decide to use Plotly with ipWidgets in JupyterLab vs. bk-plot in JupyterLab with ipWidgets. I assume it's based upon the Grammar of Graphics.
1) Is bq-plot based upon Bokah?
2) Is it based upon D3?

If you could point me in the direction of some more background information, use in JupyterLab, financial data applications, or comparisons with Plotly, any of that would be much appreciated!
Thanks!

**Comment by martinRenou** [comment]
bqplot is based on ipywidgets, which makes it communicate back-and-forth between the Python process (user API) and the JavaScript front-end (user interface), this way the plot can be dynamically updated from Python. For example, if you are making a stock price chart, you can make a simple Python function that updates your plot dynamically when a new price and volume information arrives.

It is not based on Bokeh, but it is based on D3, and it uses the Grammar of Graphics indeed.

You can give bqplot a try without the need of installing it on your machine by using this binder: https://mybinder.org/v2/gh/bqplot/bqplot/stable?filepath=examples/Index.ipynb. There you will find many examples.

**Comment by russ-mcbride** [comment]
That binder is incredibly helpful, Martin, thanks! It seems like deep integration with I-widgets could allows for some robust interactivity. And things seem cleaner, less cumbersome, perhaps better state handling, and perhaps more oriented to handling financial data (which will be my focus). Are there any plans for anything like the the chart studio ipwidgets integration for bqplot that Plotly now has?

**Comment by martinRenou** [comment]
> Are there any plans for anything like the the chart studio ipwidgets integration for bqplot that Plotly now has?

I am not familiar with this, do you have any links?

bqplot being based on ipywidgets, it perfectly integrates with it. And you can easily create complex interfaces with many different widgets. See these advanced examples using Voila bqplot and ipywidgets:
https://github.com/voila-dashboards/voila-material 

It also comes with a binder ;) https://mybinder.org/v2/gh/voila-dashboards/voila-material/stable?urlpath=voila

**Comment by russ-mcbride** [comment]
Sorry for inclination to think through some comparisons with Plotly. I'm trying to decide on whether to use Plotly+ipywidgets+chart studio or use bkplot+ipwidgets for a huge amount of visualization work (mostly financial) going forward.

Here is John Meese introducing Plotly Chart Editor integration into JupyterLab and I-widgets (you can skip to around 11:00): [https://www.youtube.com/watch?v=zR7G2tNVo1Q](https://www.youtube.com/watch?v=zR7G2tNVo1Q) 
I don't think the editor is not a full replication of Plotly's Chart Studio but I've never really used Chart Editor myself so I don't know.

What I immediately like about bqplot is the deep integration with ipywidgets (frankly, coding up interactivity in Dash is a huge pain, especially with no non-hacky way of keeping track of state). Being able to quickly tweak some things (labels, annotations, etc.) via a simple GUI in the new ipywidgets chart editor though, is nice and fast and very cool though.

Correct me if I'm wrong on this: The fact that everything is a widget in a bqplot visualization should make control and interactivity much easier than other visualization libraries. 

I'm worried about the learning curve of bkplot and current lack of documentation to get up to speed, especially with more advanced features, modifications, integration with, e.g., TA-Lib indicators, extensive "annotations", etc. Should I be? I'm also wondering how much of D3 is currency covered by bkplot. I gather some (most?) of the 2-d libraries?

Is it easy to export into a web page? With Plotly, I can (with some effort) bring in results into a Flask web app. Can I export a bqplot as html? Or as a PDF or PNG?

Thanks for chatting.

**Comment by martinRenou** [comment]
> I'm worried about the learning curve of bkplot and current lack of documentation to get up to speed

Indeed bqplot is lacking some documentation, but the example directories contain many well-made example that will help you learn. The bqplot classes also contain docstrings that document each class properly.

> Is it easy to export into a web page?

With Voila you can make a web app (with a live Python kernel on the server) out of a Jupyter Notebook very easily. See https://github.com/voila-dashboards/voila-material for example.

> Can I export a bqplot as html? Or as a PDF or PNG?

You can using the Figure's `save_png` or `save_svg` methods.

**Comment by russ-mcbride** [comment]
Hi Martin, I sent you an emai from my ucmerced.edu address.
