### ISSUE TITLE
ColorAxis does not display on Map Mark if tick_format is empty

### ISSUE THREAD

**Issue by kaiayoung** [bqplot/bqplot#1356]
See the sample code from the example notebooks:
```python
from bqplot import *
sc_geo = Mercator()
sc_c1 = ColorScale(scheme='YlOrRd')
map_styles = {'color': {643: 105., 4: 21., 398: 23., 156: 42., 124:78., 76: 98.},
              'scales': {'projection': sc_geo, 'color': sc_c1}, 'colors': {'default_color': 'Grey'}}

axis = ColorAxis(scale=sc_c1, tick_format='.2f')
chloro_map = Map(map_data=topo_load('map_data/WorldMap.json'), **map_styles)
Figure(marks=[chloro_map], axes=[axis],title='Choropleth Example')
```
![mapaxis](https://user-images.githubusercontent.com/26637211/120343623-ba8f0d00-c2ad-11eb-8d03-488428819c19.png)

**Comment by kaiayoung** [comment]
Seems to actually be the same issue as #1345?

**Comment by martinRenou** [comment]
This issue seems to be fixed by https://github.com/bqplot/bqplot/pull/1341 although this PR needs to be rebased

![ticks](https://user-images.githubusercontent.com/21197331/120643926-09d46980-c477-11eb-9fdb-3a03b1a1f2b7.png)
