### ISSUE TITLE
Pyplot - Can't save a png if the title has an accent

### ISSUE THREAD

**Issue by KevoBernardo** [bqplot/bqplot#1367]
Hi. I love your library, thank you very much

I found a bug in bqplot.pyplot (i'm using the 0.12.26 version):

If the figure's title has an accent, the "save" button (to export a png file of the figure) doesn't work. Spanish and other languages uses accents over some vocals

You can check it with the next simple example:

```
from bqplot import pyplot as plt
import numpy as np

size = 100
np.random.seed(0)
x = np.arange(size)
y = np.cumsum(np.random.randn(size)  * 100.0)

figure = plt.figure(title="Interpolación")
scatter = plt.scatter(x,y)
plt.show()
```

If the figure was named "Interpolation", it can be exported to png without problems

It's kind of silly, but it would be great if you guys could fix it

Greetings from Argentina

**Comment by martinRenou** [comment]
Thanks for reporting
