### ISSUE TITLE
Dragging of points in scatter is not working

### ISSUE THREAD

**Issue by afonit** [bqplot/bqplot#1369]
jupyterlab = 3.0.15
bqplot = 0.12.29

I was trying to build out a plot with some ipywidgets and went to add some interactivity of dragging points - but they would not move on the plot.

I then returned to the documentation and was executing this notebook to see what I was missing:
https://github.com/bqplot/bqplot/blob/master/examples/Marks/Object%20Model/Scatter.ipynb

I noticed in that notebook, the points also aren't moving.  I have reduced the notebook down to the section that has the example for the moving points:
```python
import numpy as np
import pandas as pd
from bqplot import (
    Axis, ColorAxis, LinearScale, DateScale, DateColorScale, OrdinalScale,
    OrdinalColorScale, ColorScale, Scatter, Lines, Figure, Tooltip
)
from ipywidgets import Label

size = 100
x_data = range(size)
y_data = np.cumsum(np.random.randn(size) * 100.0)

## Enabling moving of points in scatter. Try to click and drag any of the points in the scatter and 
## notice the line representing the mean of the data update
sc_x = LinearScale()
sc_y = LinearScale()

scat = Scatter(x=x_data[:10], y=y_data[:10], scales={'x': sc_x, 'y': sc_y}, colors=['orange'],
               enable_move=True)
lin = Lines(x=[], y=[], scales={'x': sc_x, 'y': sc_y}, line_style='dotted', colors=['orange'])

def update_line(change=None):
    with lin.hold_sync():
        lin.x = [np.min(scat.x), np.max(scat.x)]
        lin.y = [np.mean(scat.y), np.mean(scat.y)]

update_line()
# update line on change of x or y of scatter
scat.observe(update_line, names=['x'])
scat.observe(update_line, names=['y'])

ax_x = Axis(scale=sc_x)
ax_y = Axis(scale=sc_y, tick_format='0.2f', orientation='vertical')

fig = Figure(marks=[scat, lin], axes=[ax_x, ax_y])
fig
```

I am looking for someone to try to reproduce - if they move for them or not?

here is an animated give of what I am seeing:
![not_moving](https://user-images.githubusercontent.com/1798497/121234332-9ad58700-c861-11eb-9500-fe34175eb573.gif)

In the chrome web console I am seeing lots of errors

<details>
Error: widget model not found
    at x.get_model (523.fa256ee012d38a89b65a.js:1)
    at u.renderModel (523.fa256ee012d38a89b65a.js:1)

102568.2ffd16368ca616eca759.js?v=2ffd16368ca616eca759:1 Uncaught TypeError: Cannot read property 'x' of null
    at h.on_drag (568.2ffd16368ca616eca759.js?v=2ffd16368ca616eca759:1)
    at SVGGElement.<anonymous> (568.2ffd16368ca616eca759.js?v=2ffd16368ca616eca759:1)
    at ct.apply (693.bdce231db58bf853b2df.js?v=bdce231db58bf853b2df:1)
    at yn (693.bdce231db58bf853b2df.js?v=bdce231db58bf853b2df:1)
    at Object.a [as mouse] (693.bdce231db58bf853b2df.js?v=bdce231db58bf853b2df:1)
    at p (693.bdce231db58bf853b2df.js?v=bdce231db58bf853b2df:1)
    at 693.bdce231db58bf853b2df.js?v=bdce231db58bf853b2df:1
</details>

**Comment by KevoBernardo** [comment]
That works for me. I see that you are using Jupyter Lab. Did you have execute this line in the Anaconda Prompt when you installed bqplot?

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

**Comment by afonit** [comment]
Hello @KevoBernardo , thanks for trying it out,
I did not do the command you mentioned because that is only required under the below condition:
If you are using JupyterLab <=2

Since I am on 3.x I only have to do:
```bash
conda install -c conda-forge bqplot
```

So far - the only thing not working is the drag

**Comment by afonit** [comment]
A few new environments later and it is working - not sure why it seems to be so sensitive on install or if it is something local.  I will reopen if I get more details on what causes it.
