### ISSUE TITLE
How to ask save_png not to pop up a file dialog when filename is given?

### ISSUE THREAD

**Issue by pllim** [bqplot/bqplot#1393]
`figure.save_png(filename)` pops up a file dialog on Chrome. I don't need it because I am already giving it a filename with full path. How do I disable the file dialog?

**Comment by pllim** [comment]
Closed by accident.

**Comment by maartenbreddels** [comment]
What do you want to behavior to be?
PS: The filename is just a filename hint to the browser, it's not a full path, you cannot save to a particular path on the client if that's what you want.

**Comment by pllim** [comment]
> save to a particular path

Alas, that is what I want. Calls the API with given filename, gets a file written, no file dialog.

**Comment by pllim** [comment]
If you can somehow give me the Numpy array of the data to save, I can possibly use `scikit-image` to do that without the front-end limitation.

https://scikit-image.org/docs/dev/api/skimage.io.html#skimage.io.imsave

**Comment by maartenbreddels** [comment]
That is possible with https://ipywebrtc.readthedocs.io/en/latest/ImageRecorder.html but you cannot wait for that in a sync way (e.g. you can do `image_data = get_image_data(fig)`, it needs to go through callbacks, possibly using some wrapper with async/await.

**Comment by pllim** [comment]
> it needs to go through callbacks

Not sure what that means for me on the Python side... Is this something Mario can help with?

**Comment by martinRenou** [comment]
Fixed by #1397
