### ISSUE TITLE
CI: Galata does not test anything

### ISSUE THREAD

**Issue by maartenbreddels** [bqplot/bqplot#1399]
The zip `ui-test-output.zip` produced from Galata at https://github.com/bqplot/bqplot/pull/1397/checks is 'empty' (contain no screenshots).
Not sure if this is a misuse of Galata or a bug (cc @mbektas)
The report looks like:
![image](https://user-images.githubusercontent.com/1765949/130614537-73b57ff5-80b5-4fd8-b0a8-771481c8df04.png)

**Comment by maartenbreddels** [comment]
@martinRenou told me this is expected since there is no diff, no images are attached.

**Comment by mbektas** [comment]
@maartenbreddels `-discard-matched-captures` flag controls this behavior, if it is on then captures that match the references will be deleted when tests finish. Purpose is to save disk space. Flag is on by default (https://github.com/jupyterlab/galata#command-line-options).
