### ISSUE TITLE
How to highlight points in a scatter plot

### ISSUE THREAD

**Issue by AspirnQnt** [bqplot/bqplot#1401]
How to highlight a specific point (in the form of marker color) in the bqplot scatter diagram

**Comment by martinRenou** [comment]
```python
scatt.selected_style = {'fill': 'red'}
scatt.selected = [0, 10]
```

**Comment by AspirnQnt** [comment]
Thanks for the instant reply!!!

**Comment by AspirnQnt** [comment]
The solution is working but as per my requirement i am sizing the scatter dots as per the values of another variable.  Is it possible to  show a circle around the point of interest so that its noticeable?

**Comment by martinRenou** [comment]
This might be possible using another Scatter object, with `fill=False`, a size that's slightly more important than the original scatter, and using the positions of the points you want to highlight?
