### ISSUE TITLE
Graph mark's text stays black when switching JupyterLab's theme from Light to Dark

### ISSUE THREAD

**Issue by afonit** [bqplot/bqplot#1437]
Use the Mobile Patent Suits example from the examples folder - have JupyterLab in the dark theme, the text in the plot (except for the title) is all black and unreadable.

Below, I show what usually happens, vs what happens with the Graph mark:
(note, in the Scatter example the text goes from black to white, in the Graph example the text is black and stays black)
![image](https://user-images.githubusercontent.com/1798497/149936625-688b1d89-6f71-4c5d-b318-40afb6e86025.png)

**Comment by martinRenou** [comment]
Thanks for reporting!

**Comment by afonit** [comment]
I just upgraded to `bqplot 0.12.33`:
![image](https://user-images.githubusercontent.com/1798497/185996272-a7e6cc33-0cb9-4529-92d2-fc0e4262411c.png)

As this appears to be resolved I am going to close this issue.
