### ISSUE TITLE
Remove scientific notation on axes

### ISSUE THREAD

**Issue by etroci** [bqplot/bqplot#1450]
I created a post about this on [stackoverflow](https://stackoverflow.com/questions/70910467/how-to-remove-scientific-notation-on-bqplot). Please let me know if I should rewrite it on here as I'm not sure about the convention (this is my first time putting an issue on github). Thank you!

**Comment by martinRenou** [comment]
Thanks for opening an issue :) I answered on your StackOverflow post

**Comment by etroci** [comment]
Hey man thanks somuch for your reply it resolved my problem easily.

**Comment by martinRenou** [comment]
Sure! Please mark my stackoverflow answer as the right answer if you can :)
