### ISSUE TITLE
Support marker style "." for pyplot

### ISSUE THREAD

**Issue by pllim** [bqplot/bqplot#1457]
https://github.com/bqplot/bqplot/blob/f0b51fb09f75f4bb562312e261d7d0b452880b3c/bqplot/pyplot.py#L96-L97

Matplotlib has "." marker style. It is great for scatter plot when there are a lot of clustered data points.

**Comment by pllim** [comment]
p.s. Setting `default_size=1` for marker style `ko` works though it is not intuitive.

**Comment by mwcraig** [comment]
What size should these be drawn at do you think? I don't remember if these change size in matplotlib. Could add this to #1506 today.

**Comment by pllim** [comment]
Lemme dig out the code... I have a setting that is equivalent to "." but using native bqplot OOP syntax.

**Comment by pllim** [comment]
@mwcraig , does this help?

https://github.com/spacetelescope/jdaviz/blob/d24f8239ac0e1571b4926f2afdb9abf188033951/jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py#L382

**Comment by mwcraig** [comment]
Ah, so is the desire here just for a `.` that does that as a shortcut?

**Comment by pllim** [comment]
As far as my eyes are concerned, yes.

**Comment by mwcraig** [comment]
Also, should I make the shortcut for the crosshair "x" so that it matches matplotlib?

**Comment by mwcraig** [comment]
`.` has been added to #1506

**Comment by pllim** [comment]
> so that it matches matplotlib?

Would be nice. 🐱

**Comment by mwcraig** [comment]
> > so that it matches matplotlib?
> Would be nice. 🐱

Done -- unfortunately, the shortcut `+` is already taken in bqplot and means an outlined plus sign so that one doesn't match.

**Comment by pllim** [comment]
Hmmm... Isn't that a bug? I thought the pyplot here is for matplotlib compat?
