### ISSUE TITLE
Cannot build bqplot 0.12.x from source

### ISSUE THREAD

**Issue by pllim** [bqplot/bqplot#1498]
I started see this error when trying to build bqplot from source from your v0.12.x branch. How to fix? Thanks!

```
Building wheel for bqplot (pyproject.toml): finished with status 'error'
...
      $ jupyter labextension build .
      Building extension in .
      An error occurred.
      ValueError: Extensions require a devDependency on @jupyterlab/builder@^3.4.1, you have a dependency on 3.0.9
```

cc @maartenbreddels 

xref https://github.com/spacetelescope/jdaviz/pull/1314#issuecomment-1125179704

**Comment by martinRenou** [comment]
Thanks, this should be fixed upstream https://github.com/jupyterlab/jupyterlab/pull/12571

**Comment by pllim** [comment]
Thank you!
