### ISSUE TITLE
Bars opacities doesnt cycle

### ISSUE THREAD

**Issue by dmadeka** [bqplot/bqplot#443]
@ibdafna1

**Comment by ssunkara1** [comment]
I think this is a conscious choice rather than a bug. The documentation states, `Defaults to 1 when the list is too short, or the element of the list is set to None.` It is the same for `Lines` etc too. Having said that, I don't know if this is the right choice or not.

**Comment by rmenegaux** [comment]
I think the opacities should cycle:
- It is consistent with other marks
- As of now to modify the `Bar`/`Hist` opacity as a whole (most common usecase), we have to give it a list of `n` equal floats, where `n` is the number of bars (number of bins in the `Hist`)

**Comment by dmadeka** [comment]
@rmenegaux im with you

**Comment by martinRenou** [comment]
Fixed by https://github.com/bqplot/bqplot/pull/1121
