### ISSUE TITLE
Trouble with new ipywidgets?

### ISSUE THREAD

**Issue by mglerner** [bqplot/bqplot#449]
Hi all,

On OS X, if I make an environment with

conda create -n py3.5 python=3.5 matplotlib bqplot numpy ipywidgets notebook jupyter -c conda-forge

The standard pyplot examples produce no output. E.g.

from bqplot import pyplot as plt
import numpy as np

plt.figure(1, title='Line Chart')
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x, y)
plt.show()

gives a control bar, but no actual plot.

I have similar results with python 3.6 and a pip-installed bqplot.

I'm running off for a minute, so here's everything in that conda environment:

The following NEW packages will be INSTALLED:

    appnope:            0.1.0-py35_0                  conda-forge
    blas:               1.1-openblas                  conda-forge
    bleach:             1.5.0-py35_0                  conda-forge
    bqplot:             0.8.4-py35_0                  conda-forge
    ca-certificates:    2017.1.23-0                   conda-forge
    certifi:            2017.1.23-py35_0              conda-forge
    cycler:             0.10.0-py35_0                 conda-forge
    decorator:          4.0.11-py35_0                 conda-forge
    entrypoints:        0.2.2-py35_1                  conda-forge
    freetype:           2.7-1                         conda-forge
    html5lib:           0.999-py35_0                             
    icu:                54.1-0                                   
    ipykernel:          4.5.2-py35_0                  conda-forge
    ipython:            5.3.0-py35_0                  conda-forge
    ipython_genutils:   0.1.0-py35_0                  conda-forge
    ipywidgets:         6.0.0-py35_0                  conda-forge
    jinja2:             2.9.5-py35_0                  conda-forge
    jsonschema:         2.5.1-py35_0                  conda-forge
    jupyter:            1.0.0-py35_0                  conda-forge
    jupyter_client:     5.0.0-py35_0                  conda-forge
    jupyter_console:    5.1.0-py35_0                  conda-forge
    jupyter_core:       4.3.0-py35_0                  conda-forge
    libgfortran:        3.0.0-0                       conda-forge
    libpng:             1.6.28-0                      conda-forge
    libsodium:          1.0.10-0                      conda-forge
    markupsafe:         0.23-py35_1                   conda-forge
    matplotlib:         2.0.0-np112py35_2             conda-forge
    mistune:            0.7.3-py35_1                  conda-forge
    nbconvert:          5.1.1-py35_0                  conda-forge
    nbformat:           4.2.0-py35_0                  conda-forge
    ncurses:            5.9-10                        conda-forge
    notebook:           4.4.1-py35_0                  conda-forge
    numpy:              1.12.0-py35_blas_openblas_200 conda-forge [blas_openblas]
    openblas:           0.2.19-1                      conda-forge
    openssl:            1.0.2h-3                      conda-forge
    pandas:             0.19.2-np112py35_1            conda-forge
    pandoc:             1.19.2-0                      conda-forge
    pandocfilters:      1.4.1-py35_0                  conda-forge
    pexpect:            4.2.1-py35_0                  conda-forge
    pickleshare:        0.7.3-py35_0                  conda-forge
    pip:                9.0.1-py35_0                  conda-forge
    prompt_toolkit:     1.0.13-py35_0                 conda-forge
    ptyprocess:         0.5.1-py35_0                  conda-forge
    pygments:           2.2.0-py35_0                  conda-forge
    pyparsing:          2.1.10-py35_0                 conda-forge
    pyqt:               5.6.0-py35_2                             
    python:             3.5.3-1                       conda-forge
    python-dateutil:    2.6.0-py35_0                  conda-forge
    pytz:               2016.10-py35_0                conda-forge
    pyzmq:              16.0.2-py35_1                 conda-forge
    qt:                 5.6.2-0                                  
    qtconsole:          4.2.1-py35_0                  conda-forge
    readline:           6.2-0                         conda-forge
    setuptools:         33.1.0-py35_0                 conda-forge
    simplegeneric:      0.8.1-py35_0                  conda-forge
    sip:                4.18-py35_1                   conda-forge
    six:                1.10.0-py35_1                 conda-forge
    sqlite:             3.13.0-1                      conda-forge
    terminado:          0.6-py35_0                    conda-forge
    testpath:           0.3-py35_0                    conda-forge
    tk:                 8.5.19-1                      conda-forge
    tornado:            4.4.2-py35_0                  conda-forge
    traitlets:          4.3.1-py35_0                  conda-forge
    traittypes:         0.0.6-py35_0                  conda-forge
    wcwidth:            0.1.7-py35_0                  conda-forge
    wheel:              0.29.0-py35_0                 conda-forge
    widgetsnbextension: 2.0.0-py35_0                  conda-forge
    xz:                 5.2.2-0                       conda-forge
    zeromq:             4.2.1-1                       conda-forge
    zlib:               1.2.11-0                      conda-forge

**Comment by dmadeka** [comment]
@mglernet we haven't pushed the 0.9 to conda forge yet. Can you try the pip install with --pre if possible?

**Comment by mglerner** [comment]
pip install --pre bqplot

gave me bqplot-0.9.0b10

Which, on my system, produced a different error. This time, instead of a control bar at the bottom, I got this error:

Could not create model:
Model name	FigureModel
Model module	bqplot
Model module version	*
Script error for "bqplot" http://requirejs.org/docs/errors.html#scripterror
Could not create model:
Model name	ToolbarModel
Model module	bqplot
Model module version	*
Script error for "bqplot" http://requirejs.org/docs/errors.html#scripterror

**Comment by mglerner** [comment]
I'm also happy to use versions that aren't the most bleeding edge. Do you happen to know if there's a combination of ipywidgets + bqplot + jupyter that is known to work together, and that would allow me to use the "Save Notebook with Widgets" option?

Regardless of the answer to the above, thanks for all of you excellent work!

**Comment by SylvainCorlay** [comment]
Save notebook with widgets is a new functionnality of ipywidgets 6.0. You need a beta version of bqplot for this. We will certainly release a new version of bqplot in the next 48 hours to be compatiblw with ipywidhets 6.0 and this feature.

**Comment by mglerner** [comment]
48 hours sounds awesome! I'll stop bugging you in the interim, and let you do your work :)

**Comment by mglerner** [comment]
I'm probably clueless enough that I'd be less-than-useful as a direct contributor here. So, I thought I'd chime back in and say thanks for your work so far!

**Comment by dmadeka** [comment]
Hi @mglerner thanks so much for your feedback. Contributing to bqplot is very easy, I promise. We should set up a contributing guide.

We're trying to squeeze in a few last things before we make a release, should be soon! For now, a pip install --pre might help, since our beta releases are compatible with ipywidgets 6

**Comment by mglerner** [comment]
Hi @dmadeka,

I'm getting the above error with bqplot 0.9.0.b10 and ipywidgets 6.0.0. It's in the conda environment described above, and I'm happy to upgrade/reinstall whatever parts of it would be useful for testing; I'm only using it to try to get bqplot's matplotlib interface + ipywidgets's "Save With Widgets" running happily.

**Comment by ibdafna1** [comment]
@dmadeka I'm getting the same error

**Comment by dmadeka** [comment]
@ibdafna1 @mglerner I did the following and it worked:

``` bash
conda create --name=test jupyter ipywidgets scipy setuptools
source activate test
pip install --upgrade ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension
pip install --pre bqplot
jupyter nbextension enable --py --sys-prefix bqplot
```

Here is my environment:

```
conda list
# packages in environment at /home/dhruv/anaconda2/envs/test:
#
appdirs                   1.4.3                     <pip>
bleach                    2.0.0                     <pip>
bleach                    1.5.0                    py36_0  
bqplot                    0.9.0b10                  <pip>
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
entrypoints               0.2.2                    py36_1  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
html5lib                  0.999                    py36_0  
html5lib                  0.999999999               <pip>
icu                       54.1                          0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
ipywidgets                6.0.0                     <pip>
jinja2                    2.9.5                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.0                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
markupsafe                0.23                     py36_2  
MarkupSafe                1.0                       <pip>
mistune                   0.7.3                    py36_0  
mkl                       2017.0.1                      0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
notebook                  4.3.1                    py36_0  
notebook                  4.4.1                     <pip>
numpy                     1.12.0                   py36_0  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.19.2                    <pip>
pandocfilters             1.4.1                    py36_0  
path.py                   10.1                     py36_0  
pcre                      8.39                          1  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.9                    py36_0  
ptyprocess                0.5.1                    py36_0  
pygments                  2.2.0                    py36_0  
pyparsing                 2.2.0                     <pip>
pyqt                      5.6.0                    py36_2  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2016.10                   <pip>
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtconsole                 4.2.1                    py36_1  
readline                  6.2                           2  
scipy                     0.18.1              np112py36_1  
setuptools                27.2.0                   py36_0  
setuptools                34.3.2                    <pip>
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.5.18                        0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.2                    py36_0  
traittypes                0.0.6                     <pip>
wcwidth                   0.1.7                    py36_0  
webencodings              0.5                       <pip>
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                     <pip>
widgetsnbextension        1.2.6                    py36_0  
xz                        5.2.2                         1  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  
```

**Comment by dmadeka** [comment]
@ibdafna1 @mglerner I did the following and it worked:

``` bash
conda create --name=test jupyter numpy scipy setuptools
source activate test
pip install --upgrade ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension
pip install --pre bqplot
jupyter nbextension enable --py --sys-prefix bqplot
```

Here is my environment:

```
conda list
# packages in environment at /home/dhruv/anaconda2/envs/test:
#
appdirs                   1.4.3                     <pip>
bleach                    2.0.0                     <pip>
bleach                    1.5.0                    py36_0  
bqplot                    0.9.0b10                  <pip>
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
entrypoints               0.2.2                    py36_1  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
html5lib                  0.999                    py36_0  
html5lib                  0.999999999               <pip>
icu                       54.1                          0  
ipykernel                 4.5.2                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.1.0                    py36_0  
ipywidgets                5.2.2                    py36_1  
ipywidgets                6.0.0                     <pip>
jinja2                    2.9.5                    py36_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.0                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
markupsafe                0.23                     py36_2  
MarkupSafe                1.0                       <pip>
mistune                   0.7.3                    py36_0  
mkl                       2017.0.1                      0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
notebook                  4.3.1                    py36_0  
notebook                  4.4.1                     <pip>
numpy                     1.12.0                   py36_0  
openssl                   1.0.2k                        1  
packaging                 16.8                      <pip>
pandas                    0.19.2                    <pip>
pandocfilters             1.4.1                    py36_0  
path.py                   10.1                     py36_0  
pcre                      8.39                          1  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.9                    py36_0  
ptyprocess                0.5.1                    py36_0  
pygments                  2.2.0                    py36_0  
pyparsing                 2.2.0                     <pip>
pyqt                      5.6.0                    py36_2  
python                    3.6.0                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2016.10                   <pip>
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         3  
qtconsole                 4.2.1                    py36_1  
readline                  6.2                           2  
scipy                     0.18.1              np112py36_1  
setuptools                27.2.0                   py36_0  
setuptools                34.3.2                    <pip>
simplegeneric             0.8.1                    py36_1  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.5.18                        0  
tornado                   4.4.2                    py36_0  
traitlets                 4.3.2                    py36_0  
traittypes                0.0.6                     <pip>
wcwidth                   0.1.7                    py36_0  
webencodings              0.5                       <pip>
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                     <pip>
widgetsnbextension        1.2.6                    py36_0  
xz                        5.2.2                         1  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  
```

![image](https://cloud.githubusercontent.com/assets/7892382/23836601/553c2a80-0751-11e7-99ef-3270b983fee7.png)

**Comment by dmadeka** [comment]
Works without python=3 as well for me

**Comment by mglerner** [comment]
That seems to work for me on my machine. I definitely wasn't doing the "jupyter nbextensions enable" bit before.

The "Save Widget State" didn't work on nbviewer for me: 

http://nbviewer.jupyter.org/github/mglerner/MathematicalPhysics/blob/master/SimpleTests/SimpleTests.ipynb

For what it's worth, the ipywidgets install failed the first time with an error chain ending in

FileNotFoundError: [Errno 2] No such file or directory: '/Users/mglerner/anaconda3/envs/bqplot/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg'

but running the command again worked.

**Comment by dmadeka** [comment]
@mglerner That happened with me as well, @SylvainCorlay might be the right person to address this. Not sure why the Save Widget State didnt work - @SylvainCorlay any ideas?

**Comment by SylvainCorlay** [comment]
No idea on the setuptools error. cc @jasongrout

**Comment by jasongrout** [comment]
I'm not sure what is going on with setuptools there either.

It looks like the save widget state did *something* - the interact is creating a slider. However, looking in that raw file, I see this cell, for example:

```
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ae557c5b1b1442f898fdbf7c3b479d47"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.plot([0,1,2],[0,1,5])\n",
    "plt.show()"
   ]
  },
```
Searching the document for `ae557c5b1b1442f898fdbf7c3b479d47` doesn't yield anything, so it appears that the bqplot model didn't get saved.

**Comment by jasongrout** [comment]
Instead, it looks like different bqplot models were saved in the notebook file. I'm not sure what would cause that. @SylvainCorlay?

**Comment by mglerner** [comment]
In a perhaps-misguided attempt to be helpful, I just reran the notebook. The reason it said In[3] instead of In[1] last time was that I had left out the plt.clear() line the first time. So, this time I ran it with just the code you see.

Having done that, the result is essentially the same. But, I think the relevant model id is `5f49855455764c5c9ed027dab92fbfcf`. I still see `ae557c5b1b1442f898fdbf7c3b479d47` but it's not the one connected to the relevant widget.

**Comment by mglerner** [comment]
OK. Here's a better test case:

http://nbviewer.jupyter.org/github/mglerner/MathematicalPhysics/blob/master/SimpleTests/Untitled.ipynb

I entered the code you see, told it to save the notebook with the widgets, and pushed. In this case, the relevant model_id is `0397ae747e78479abd9f6f24d7bee929` which does get referenced a bit later in the notebook file. Hopefully removing cruft from the test case helps.

**Comment by jasongrout** [comment]
@mglerner, interacts don't work right now with static web pages. The first step would be https://github.com/ipython/ipywidgets/issues/1183.

**Comment by dmadeka** [comment]
@mglerner Im so sorry for the delay. @jasongrout has not mentioned, bqplot does not require interact. We built it as a widget, so if you do 

``` python
fig = plt.figure()
line = plt.plot([1, 2,3], [1, 2, 3])
fig
```

you can simply do

``` python
line.y = [3, 4, 5]
```

Alternately if you have a function, please try

```
from ipywidgets import FloatSlider

n = FloatSlider()

def changed(change):
    line.y = np.arange(1, 4)**n

n.observe(changed, 'value')
```

What this is doing is tying the Slider to the y values of the chart, there is no need to recall `plt.figure()` bqplot itself is a widget

**Comment by mglerner** [comment]
I got a comment via email, but somehow it isn't showing up here. When I do

`conda create -n bqplot matplotlib bqplot numpy ipywidgets notebook jupyter -c conda-forge`

It grabs the recently-released bqplot 0.9.0 and ipywidgets 6.0.0, all for python 3.6.

In any case, that gives me a version that doesn't need to use interact, and works locally. It looks better view the nbviewer, but doesn't quite work.

http://nbviewer.jupyter.org/github/mglerner/MathematicalPhysics/blob/master/SimpleTests/NoInteract.ipynb

**Comment by dmadeka** [comment]
@mglerner So, python callbacks are not yet supported by nbconvert. The kernel itself would have to be exported in some way right, if a python function is being called?

**Comment by mglerner** [comment]
@dmadeka That sounds reasonable to me, but I don't know how this works behind the scenes. I think another option would be to export a bunch of static images/frames, like Jake Vanderplas's static widgets used to, but I assume you folks have good reasons for not doing that. 

I suppose that, if I'm going to keep pestering you with bug reports/comments, I should do some reading to find out what the strategy for this actually is.

**Comment by dmadeka** [comment]
@mglerner the hover, tooltip drag etc work if you can do it without a Python callback:

http://nbviewer.jupyter.org/github/bloomberg/bqplot/blob/master/examples/Applications/Wealth%20of%20Nations.ipynb

**Comment by martinRenou** [comment]
I believe it's safe to close this issue now. Please reopen it if you think otherwise.
