### ISSUE TITLE
Cannot embed bqplot widget to a html

### ISSUE THREAD

**Issue by DandikUnited** [bqplot/bqplot#527]
I've created a scatter plot with interactive elements in a `VBox` it works fine in my jupyter notebook.

When I export widgets using embed widgets and paste in a html file ipywidgets and plot comes up. When I change slider, plot remains same.

In chrome's console I can see that bqplot.js I see this
<img width="576" alt="screen shot 2017-08-08 at 4 03 09 pm" src="https://user-images.githubusercontent.com/3067070/29098230-24d419b2-7c53-11e7-8597-c33f7a385332.png">

Is it possible to have that plot with interactivity in a HTML page?

**Comment by SylvainCorlay** [comment]
That should work. This is what we use here for example: http://jupyter.org/widgets

This error message is not significant though because we always check the local path before reaching to the CDN so this error message will always be there even when it works.

**Comment by SylvainCorlay** [comment]
Can you provide some information about the versions at play etc?

**Comment by QuentinAndre** [comment]
I think Dandik's problem (and the one I am also facing right now) is that the link between ipywidgets and bqplot is going through the Python back-end. As such, when embedded into a web page, bqplot objects cannot be interacted with through ipywidgets.

An example from the [Wealth  of Nations](https://github.com/bloomberg/bqplot/blob/master/examples/Applications/Wealth%20of%20Nations.ipynb) notebook:

When embedded into a webpage, the `play_button` and the `year_slider` are linked using ``jslink``. It ensures that they correctly interact with each other when embedded in an HTML webpage.

    play_button = Play(min=1800, max=2008, interval=time_interval)
    jslink((play_button, 'value'), (year_slider, 'value'))
    v = VBox([HBox([play_button, year_slider]), fig])

On the other hand, the link between the aspects of the `fig` and the `year_slider` is created using observer events:

    def year_changed(change):
        wealth_scat.x, wealth_scat.y, wealth_scat.size = get_data(year_slider.value)
        year_label.text = [str(year_slider.value)]
    year_slider.observe(year_changed, 'value')

As a consequence, this interaction is lost when embedding the widget into a webpage. 

Now, is there a way to `jslink` traits of the bqplot to other ipywidgets?

Thank you in advance for your answer!

**Comment by DougRzz** [comment]
@QuentinAndre   There is a way to jslink traits of the bqplot to other ipywidgets.  However, the traits have to be syncable and of the same type.  

Try these in the wealth of nations ipynb:

```python
# Text widget to change the width of the bqplot figure.  try typing in box 500px or 90% for example
widthWidget = widgets.Text(
    value='500px',
    placeholder='e.g. 500px or 90%',
    description='Width of Figure:',
    disabled=False
)
jslink((fig.layout, 'width'), (widthWidget, 'value'))
widthWidget 
```

or 

```python
#Slider to change minimum value on y scale of bqplot figure
xslider = IntSlider(min=0, max=100, step=1, description='Min x scale: ', value=y_sc.min)

jslink((y_sc, 'min'), (xslider, 'value'))
xslider
```
