### ISSUE TITLE
Link to mybinder fails to run examples interactively

### ISSUE THREAD

**Issue by tlinnet** [bqplot/bqplot#576]
When using the link from the README:  http://mybinder.org/repo/bloomberg/bqplot/notebooks/examples

The building of the image fails.
```
NoPackagesFoundError: Dependencies missing in current linux-64 channels:
  - bqplot -> numpy >=1.10.4 -> blas 1.1 openblas -> openblas -> libgfortran
  - bqplot -> numpy >=1.10.4 -> @blas_openblas
  - bqplot -> pandas
  - bqplot -> traittypes >=0.0.6
```

I have made a working Dockerfile, which will make mybinder launch a working _jupyter/scipy-notebook_ Docker image, copy the examples from bqplot and run it.

See here for setup: https://github.com/tlinnet/bqplot_examples

Or try run mybinder with following link: https://mybinder.org/v2/gh/tlinnet/bqplot_examples/master

**Comment by dmadeka** [comment]
@tlinnet I couldnt really access the repo

@SylvainCorlay Any ideas?

**Comment by tlinnet** [comment]
Try this instead 

https://github.com/tlinnet/jupyter_plot_examples

https://mybinder.org/v2/gh/tlinnet/jupyter_plot_examples/master 

mybinder can build images from different information. Currently your setup files in github repository fails for mybinder. Mybinder documentation suggest using a Dockerfile which uses official jupyter images. The links above show such a setup.

**Comment by dmadeka** [comment]
So that worked for me well - the bqplot plots run and everything 

Can i close the issue?

**Comment by tlinnet** [comment]
Hi.

Your README file still points to a mybinder setup, which does not work. :)


![screen shot 2017-11-30 at 09 09 43](https://user-images.githubusercontent.com/1208292/33420324-6fee14f2-d5ae-11e7-8a43-27c00e15152e.png)
![screen shot 2017-11-30 at 09 10 19](https://user-images.githubusercontent.com/1208292/33420326-71d1cb2e-d5ae-11e7-9cc4-e539baf8f18a.png)

**Comment by tlinnet** [comment]
I believe you can fix it by changing _bqplot/environment.yml_

By removing   **- nodefaults**
```
name: bqplot
channels:
  - conda-forge
dependencies:
  - bqplot
```

**- nodefaults** from https://conda.io/docs/user-guide/tasks/manage-environments.html

> Adding nodefaults to the channels list in environment.yml is similar to removing defaults from the channels list in the .condarc file.

This is probably why numpy cannot be installed.

**Comment by dmadeka** [comment]
That looks like it should work - sorry, didnt realize that link wasn't working! Can you open the PR? Since you identified the change? If not, happy to do it

**Comment by martinRenou** [comment]
I believe it's safe to close this issue now. The binder link works.
