### ISSUE TITLE
Missing events in JupyterLab

### ISSUE THREAD

**Issue by albop** [bqplot/bqplot#597]
Not sure whether this is a bqplot of Jupyterlab issue.
Consider the following code:
```
from bqplot import pyplot as plt
pl = plt.plot([0,1,2],[0,1,4],'o')
pl.observe(lambda x: print(x))
plt.show()
```
In JupyterOld, if I hover a point, it prints a list of events. In JupyterLab nothing is printed. 
This is not a printing issue since replacing the handler by a method modifying a dictionary doesn't lead to anything either.

These are the versions of `Jupyterlab` and `bqplot` I have, both installed via conda:
```
bqplot            0.10.2      py36_0    conda-forge                                                              
jupyterlab      0.31.1      py36_0    conda-forge
```

**Comment by martinRenou** [comment]
Sorry for the late answer. This is a known JupyterLab "feature". You would need to use the `Output` widget to capture any outputs and show them. See https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html?highlight=output
