### ISSUE TITLE
empty png

### ISSUE THREAD

**Issue by lincolnfrias** [bqplot/bqplot#607]
Using bqplot 0.10.1 on Ubuntu, I'm unable to save any png. It just creats an empty image. 

This happens with both APIs, either using the save widget or the `fig.save_png`.

```
from bqplot import pyplot as plt

plt.figure(title='My First Plot')
plt.plot(x_data, y_data)
plt.show()
```

```
from bqplot import *

x_sc = LinearScale()
y_sc = LinearScale()

scatter_chart = Scatter(x=x_data, y=y_data, scales={'x': x_sc, 'y': y_sc})

x_ax = Axis(label='X', scale=x_sc)
y_ax = Axis(label='Y', scale=y_sc, orientation='vertical')

fig = Figure(marks=[scatter_chart], axes=[x_ax, y_ax])
fig.save_png()
```

Any clues?

By the way, thanks a lot for such an awesome library.

**Comment by dmadeka** [comment]
You need to let the figure render before calling `save_png`. Can you try calling save_png after the figure is drawn?

**Comment by lincolnfrias** [comment]
I tried, thanks. But it did not work.

**Comment by DougRzz** [comment]
I just tested it and it works ok for me.  (Windows 10, latest Chrome)

**Comment by lincolnfrias** [comment]
Great tip, @DougRzz.  It worked on Chrome in my Ubuntu 16.04. Thanks a lot. 
So, at least in my case, it seems to be an issue in Firefox (58). I even disabled uBlock Origin, since I had problem with it on similar situations, but it didn't solve this issue.

**Comment by lincolnfrias** [comment]
I just tested in a Windows machine and again it worked on Chrome but not on Firefox.

**Comment by dmadeka** [comment]
@lincolnfrias I think we've had a good bit of issues with non-Chrome browsers. @SylvainCorlay should we consider saying Chrome is our supported browser?

**Comment by SylvainCorlay** [comment]
We primarily work with chrome indeed but I will look into this.

**Comment by tino-bsm** [comment]
I had a similar issue, but generating plots from a loop.
Tried different browsers, but they were still coming out empty.
The only way to get them to save properly was to add a sleep function for 1 second between the display and the save.
