### ISSUE TITLE
Figure object can not be resized in jupyter dashborad

### ISSUE THREAD

**Issue by HereticSK** [bqplot/bqplot#610]
I am trying to use bqplot in `jupyter dashboard`. Only cells containing bqplot `Figure`s cannot be resized in the `jupyter dashboard` grid layout. It always occupy the full width of the browser no matter how I stretch, while resizing the height works as normal. 

I also tried matplotlib plots and ipywidgets in the same environment. They both works well. So I guess this is a bqplot specific issue? 

Can anyone help?
![image](https://user-images.githubusercontent.com/17619612/36247032-5af21c78-126d-11e8-8aae-97e0919ebbed.png)

My test uses the following code:
```Python
import ipywidgets as widgets
from ipywidgets import HBox
from IPython.display import display
import numpy as np

import matplotlib.pyplot as plt
from bqplot import (
    DateScale, LinearScale, Scatter,
    Lines, Hist, 
    Axis, PanZoom,
    Figure
)

x = np.random.randn(500)
y = np.random.randn(500)

# use bqplot in one cell
sc_x = LinearScale()
sc_y = LinearScale()

ax_x = Axis(scale=sc_x, grid_lines='solid')
ax_y = Axis(scale=sc_y, orientation='vertical',
    grid_lines='solid')

sca = Scatter(x=x, y=y, scales={'x': sc_x, 'y': sc_y})
Figure(marks=[sca], axes=[ax_x, ax_y])

# use matplotlib in another cell
%matplotlib inline
plt.scatter(x, y)

# use ipywidgets in another cell
@widgets.interact(n=200)
def plot_subset(n):
    plt.scatter(x[:n], y[:n])
```

OS: Windows 10
package info:
> (bqplot-dev) >conda list -n bqplot-dev
> bqplot                    0.10.3                   py36_0    conda-forge
> ipykernel                 4.8.1                    py36_0    conda-forge
> ipython                   6.2.1                    py36_1    conda-forge
> ipython_genutils          0.2.0                    py36_0    conda-forge
> ipywidgets                7.1.1                    py36_0    conda-forge
> jupyter_client            5.2.2                    py36_0    conda-forge
> jupyter_core              4.4.0                      py_0    conda-forge
> jupyter_dashboards        0.7.0                    py36_0    conda-forge
>

**Comment by vsub21** [comment]
I am also having a similar problem not being able to resize the cell within the grid. Any pointers would be greatly appreciated!

**Comment by martinRenou** [comment]
In recent bqplot releases the plot now resizes itself so that it takes the available space. This should work smoothly in your use-case. Please feel free to reopen this issue if you still have problems.
