### ISSUE TITLE
HandDraw throws javascript errors

### ISSUE THREAD

**Issue by matthewturk** [bqplot/bqplot#971]
Running a simple `HandDraw` interaction, including the example from `Interaction Layer.ipynb`, results in lots of javascript errors when I interact.  Specifically:

```
Uncaught TypeError: Cannot read property 'line' of undefined
    at SVGPathElement.<anonymous> (HandDraw.js:116)
    at SVGPathElement.<anonymous> (attr.js:29)
    at Selection.each (each.js:5)
    at Selection.attr (attr.js:53)
    at HandDraw.mouse_entry (HandDraw.js:115)
    at HandDraw.mousedown (HandDraw.js:60)
    at SVGRectElement.<anonymous> (HandDraw.js:38)
    at SVGRectElement.<anonymous> (on.js:27)
```

**To Reproduce**

Either launch the `Interaction Layer.ipynb` notebook and execute all the cells down to and including the HandDraw example, or use this minimal working example:

```python
import bqplot
import numpy as np

bins = np.mgrid[0.0:1.0:256j]
vals = np.random.random(256)

x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

lines = bqplot.Lines(x = bins, y = vals, scales = {'x': x_sc, 'y': y_sc})
handdraw = bqplot.interacts.HandDraw(lines = lines)
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')
fig = bqplot.Figure(marks = [lines], interaction=handdraw, axes = [x_ax, y_ax])
display(fig)
```

The first time I click, the interaction works (but is jumpy and laggy) but subsequent clicks don't do anything and emit the error above.  This happens in both lab and the notebook.

**Environment (please complete the following information):**
 - Operating System and Version: Ubuntu Linux 18.04
 - Browser: Chrome Stable
 - bqplot: 0.12.1
 - bqplot jupyterlab extension: 0.5.1

Thank you for any ideas you might have!

**Comment by martinRenou** [comment]
Thank you for fixing this issue!
